### PR TITLE
Refactor account settings

### PR DESCRIPTION
**Pull request by kress95**
Took so much longer than what I've planned, but now it's ready and I'm pretty happy with the result :smile:

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/helix/37)

### CODE REVIEW

**Comment by kress95** [comment]
Damnit jenkins, don't _eff_ with me.
```
[cker_Experience_Helix_PR-37-F3WIITFK2UD7NQFM52VYCHW6KMIN7W6DXQOKEQB7SP4742MCKYKQ] Running shell script
+ mix compile
warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)
Unchecked dependencies for environment prod:
* hebroker (https://github.com/HackerExperience/HeBroker.git)
  the dependency is not available, run "mix deps.get"
* helf (https://github.com/HackerExperience/HELF.git)
  the dependency is not available, run "mix deps.get"
** (Mix) Can't continue due to errors on dependencies
script returned exit code 1
```

**Comment by mememori** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks broke.

---

*[apps/helix_account/lib/account/controller/account.ex, line 111 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/37#-Kg0iuMlOKCUzSI4X1kY:-Kg0iuMmVuhnSxsFYdO2:bx61i1s) ([raw file](https://github.com/hackerexperience/helix/blob/4390aa1b9f60d840f8add5971a921a2c4d016d6d/apps/helix_account/lib/account/controller/account.ex#L111)):*
<details><summary><i alt="summary">Quoted 32 lines of code…</i></summary>
> ```elixir
>   def put_settings(account, params) do
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>
>     settings_changeset =
>       account
>       |> AccountSetting.Query.from_account()
>       |> select([as], as.settings)
>       |> Repo.one()
>       |> Kernel.||(Setting.default())
>       |> Setting.changeset(params)
</details>
>  
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>     if settings_changeset.valid? do
>       settings =
>         settings_changeset
>         |> Ecto.Changeset.apply_changes()
>         |> Map.from_struct()
</details>
>  
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>       result =
>         %{account_id: account.account_id, settings: settings}
>         |> AccountSetting.changeset()
>         |> Repo.insert_or_update()
</details>
>  
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>
>       case result do
>         {:ok, _} ->
>           {:ok, settings}
>         # FIXME: add account not found error here
>         {:error, _} ->
>           {:error, :internal}
>       end
>     else
>       # FIXME: be more descriptive
>       {:error, :invalid_settings}
>     end
</details>
>   end
```
</details>


If `AccountSetting` defines `settings` as an embed schema, `settings` is a schema with defaults and it will receive the custom settings as params, why are you overengineering it that much ?

```elixir
def put_settings(account = %Account{}, params) do
    account_settings = Repo.one(AccountSetting, account.id) || %AccountSetting{}
    params = %{account_id: account.id, settings: params}

    changeset = AccountSetting.changeset(account_settings, params)

    case Repo.insert_or_update(changeset) do
      {:ok, %{settings: settings}} ->
        {:ok, settings}
      error = {:error, _} ->
        error
    end
  end
```

---

*[apps/helix_account/lib/account/controller/account.ex, line 139 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/37#-Kg0kIze89cq9AkrI2uS:-Kg0kIze89cq9AkrI2uT:b-2e4d8z) ([raw file](https://github.com/hackerexperience/helix/blob/4390aa1b9f60d840f8add5971a921a2c4d016d6d/apps/helix_account/lib/account/controller/account.ex#L139)):*
<details><summary><i alt="summary">Quoted 26 lines of code…</i></summary>
> ```elixir
>   def get_settings(account) do
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>     custom_settings =
>       account
>       |> AccountSetting.Query.from_account()
>       |> select([as], as.settings)
>       |> Repo.one()
</details>
>  
>     if not is_nil(custom_settings) do
>       custom_settings = Map.from_struct(custom_settings)
>  
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>       on_conflict = fn _, default_value, custom_value ->
>         if is_nil(custom_value),
>           do: default_value,
>           else: custom_value
>       end
</details>
>  
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>       merged_map =
>         Setting.default()
>         |> Map.from_struct()
>         |> Map.merge(custom_settings, on_conflict)
</details>
>  
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>       struct(Setting, merged_map)
>     else
>       Setting.default()
>     end
</details>
>   end
```
</details>


Overengineering

```elixir
def get_settings(account = %Account{}) do
    settings =
      account
      |> AccountSetting.Query.from_account()
      |> select([as], as.settings)
      |> Repo.one()

    settings || %Setting{}
  end
```

---

*[apps/helix_account/lib/account/model/setting.ex, line 11 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/37#-Kg0kqbW20G1bZfRajMs:-Kg0kqbW20G1bZfRajMt:bjn0vdi) ([raw file](https://github.com/hackerexperience/helix/blob/4390aa1b9f60d840f8add5971a921a2c4d016d6d/apps/helix_account/lib/account/model/setting.ex#L11)):*
> ```Elixir
>   @primary_key false
>   embedded_schema do
>     field :is_beta, :boolean, null: true
> ```

wrong

```elixir
field :is_beta, :boolean,
  default: false
```

---

*[apps/helix_account/lib/account/model/setting.ex, line 16 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/37#-Kg0ky9_Zf7mx8tpp8Y5:-Kg0ky9_Zf7mx8tpp8Y6:b1ttqug) ([raw file](https://github.com/hackerexperience/helix/blob/4390aa1b9f60d840f8add5971a921a2c4d016d6d/apps/helix_account/lib/account/model/setting.ex#L16)):*
> ```Elixir
>   @spec changeset(Setting.t, map) :: Ecto.Changeset.t
>   def changeset(struct \\ %__MODULE__{}, params) do
>     cast(struct, defaults_to_nil(params), @update_fields)
> ```

1) you're missing validators
2) i don't understand why would you use that `defaults_to_nil` fun

---

*[apps/helix_account/lib/account/model/setting.ex, line 22 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/37#-Kg0lBosInoNEhJyPceL:-Kg0lBosInoNEhJyPceM:baebkxv) ([raw file](https://github.com/hackerexperience/helix/blob/4390aa1b9f60d840f8add5971a921a2c4d016d6d/apps/helix_account/lib/account/model/setting.ex#L22)):*
> ```Elixir
>   def default do
>     %__MODULE__{is_beta: false}
>   end
> ```

structs have defaults

---

*[apps/helix_account/lib/account/model/setting.ex, line 38 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/37#-Kg0lE4X9JYdOTN97H_3:-Kg0lE4YW8a5HSSbPfdL:bovm4p9) ([raw file](https://github.com/hackerexperience/helix/blob/4390aa1b9f60d840f8add5971a921a2c4d016d6d/apps/helix_account/lib/account/model/setting.ex#L38)):*
> ```Elixir
>     |> Enum.map(nullify)
>     |> :maps.from_list()
>   end
> ```

why ? I mean, all you needed to do was define the embed schema with it's defaults and create a single changeset function

```elixir
def changeset(struct \\ %__MODULE__{}, params) do
  struct
  |> cast(params, @allowed_fields)
  |> validate_inclusion(:is_beta, [true, false])
end
```

---

*[apps/helix_account/test/controller/account_test.exs, line 159 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/37#-Kg0lm7L8NjBZK4KobUY:-Kg0lm7L8NjBZK4KobUZ:b-jltunp) ([raw file](https://github.com/hackerexperience/helix/blob/4390aa1b9f60d840f8add5971a921a2c4d016d6d/apps/helix_account/test/controller/account_test.exs#L159)):*
> ```Elixir
>       account = Factory.insert(:account)
> 
>       %{settings: expected} = Factory.params_for(:account_setting)
> ```

Personally i hate when you use `params_for`. It makes it hard to know what is the `"valid params"` and it is also prone to fail because `params_for` returns the kv from _"the final form"_ of a record, while your input is not the final transformed value of a k/v. See Account password as an example

---

*[apps/helix_account/test/model/setting_test.exs, line 9 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/37#-Kg0mspokqLsvg_tO1GQ:-Kg0mspokqLsvg_tO1GR:b-hpxayf) ([raw file](https://github.com/hackerexperience/helix/blob/4390aa1b9f60d840f8add5971a921a2c4d016d6d/apps/helix_account/test/model/setting_test.exs#L9)):*
> ```Elixir
>   @moduletag :unit
> 
>   test "enforces field typing" do
> ```

this is not a good name for the test. You should test each possible setting indempendently

---

*[apps/helix_account/test/model/setting_test.exs, line 13 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/37#-Kg0mnVu5Spn18dtM0B4:-Kg0mnVu5Spn18dtM0B5:bgnpf3s) ([raw file](https://github.com/hackerexperience/helix/blob/4390aa1b9f60d840f8add5971a921a2c4d016d6d/apps/helix_account/test/model/setting_test.exs#L13)):*
> ```Elixir
> 
>     refute result.valid?
>     refute :unknown_setting in Keyword.keys(result.errors)
> ```

where did this `:unknown_setting` comes from ?

---

*[apps/helix_account/test/model/setting_test.exs, line 37 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/37#-Kg0n2mqaMGeeYQjTRXo:-Kg0n2mqaMGeeYQjTRXp:bwmd1in) ([raw file](https://github.com/hackerexperience/helix/blob/4390aa1b9f60d840f8add5971a921a2c4d016d6d/apps/helix_account/test/model/setting_test.exs#L37)):*
> ```Elixir
> 
>     assert Enum.empty?(result)
>   end
> ```

what ? why ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/37)*

**Comment by kress95** [comment]
Review status: 4 of 11 files reviewed at latest revision, 11 unresolved discussions, some commit checks broke.

---

*[apps/helix_account/lib/account/controller/account.ex, line 111 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/37#-Kg0iuMlOKCUzSI4X1kY:-KgEaoE0J-AN8WK2GLBI:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/88a3f3ce688637bce5d17eaa9c9da96f3318059c/apps/helix_account/lib/account/controller/account.ex#L111)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

> ```elixir
>   def put_settings(account, params) do
>     settings_changeset =
>       account
>       |> AccountSetting.Query.from_account()
>       |> select([as], as.settings)
>       |> Repo.one()
>       |> Kernel.||(Setting.default())
>       |> Setting.changeset(params)
>  
>     if settings_changeset.valid? do
>       settings =
>         settings_changeset
>         |> Ecto.Changeset.apply_changes()
>         |> Map.from_struct()
>  
>       result =
>         %{account_id: account.account_id, settings: settings}
>         |> AccountSetting.changeset()
>         |> Repo.insert_or_update()
>  
>       case result do
>         {:ok, _} ->
>           {:ok, settings}
>         # FIXME: add account not found error here
>         {:error, _} ->
>           {:error, :internal}
>       end
>     else
>       # FIXME: be more descriptive
>       {:error, :invalid_settings}
>     end
>   end
> ```

If `AccountSetting` defines `settings` as an embed schema, `settings` is a schema with defaults and it will receive the custom settings as params, why are you overengineering it that much ?

```elixir
def put_settings(account = %Account{}, params) do
    account_settings = Repo.one(AccountSetting, account.id) || %AccountSetting{}
    params = %{account_id: account.id, settings: params}

    changeset = AccountSetting.changeset(account_settings, params)

    case Repo.insert_or_update(changeset) do
      {:ok, %{settings: settings}} ->
        {:ok, settings}
      error = {:error, _} ->
        error
    end
  end
```
</blockquote></details>

Done.

---

*[apps/helix_account/lib/account/controller/account.ex, line 139 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/37#-Kg0kIze89cq9AkrI2uS:-KgEapH8nHYv_3mUYuXQ:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/88a3f3ce688637bce5d17eaa9c9da96f3318059c/apps/helix_account/lib/account/controller/account.ex#L139)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

> ```elixir
>   def get_settings(account) do
>     custom_settings =
>       account
>       |> AccountSetting.Query.from_account()
>       |> select([as], as.settings)
>       |> Repo.one()
>  
>     if not is_nil(custom_settings) do
>       custom_settings = Map.from_struct(custom_settings)
>  
>       on_conflict = fn _, default_value, custom_value ->
>         if is_nil(custom_value),
>           do: default_value,
>           else: custom_value
>       end
>  
>       merged_map =
>         Setting.default()
>         |> Map.from_struct()
>         |> Map.merge(custom_settings, on_conflict)
>  
>       struct(Setting, merged_map)
>     else
>       Setting.default()
>     end
>   end
> ```

Overengineering

```elixir
def get_settings(account = %Account{}) do
    settings =
      account
      |> AccountSetting.Query.from_account()
      |> select([as], as.settings)
      |> Repo.one()

    settings || %Setting{}
  end
```
</blockquote></details>

Done.

---

*[apps/helix_account/lib/account/model/setting.ex, line 11 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/37#-Kg0kqbW20G1bZfRajMs:-KgEar1juwilz7k2wQMG:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/88a3f3ce688637bce5d17eaa9c9da96f3318059c/apps/helix_account/lib/account/model/setting.ex#L11)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

wrong

```elixir
field :is_beta, :boolean,
  default: false
```
</blockquote></details>

Done.

---

*[apps/helix_account/lib/account/model/setting.ex, line 16 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/37#-Kg0ky9_Zf7mx8tpp8Y5:-KgEasGAKFq80MYwG8Xb:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/88a3f3ce688637bce5d17eaa9c9da96f3318059c/apps/helix_account/lib/account/model/setting.ex#L16)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

1) you're missing validators
2) i don't understand why would you use that `defaults_to_nil` fun
</blockquote></details>

Done.

---

*[apps/helix_account/lib/account/model/setting.ex, line 38 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/37#-Kg0lE4X9JYdOTN97H_3:-KgEauqYlBGx6V-povoi:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/88a3f3ce688637bce5d17eaa9c9da96f3318059c/apps/helix_account/lib/account/model/setting.ex#L38)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

why ? I mean, all you needed to do was define the embed schema with it's defaults and create a single changeset function

```elixir
def changeset(struct \\ %__MODULE__{}, params) do
  struct
  |> cast(params, @allowed_fields)
  |> validate_inclusion(:is_beta, [true, false])
end
```
</blockquote></details>

Done.

---

*[apps/helix_account/test/controller/account_test.exs, line 161 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/37#-KgF1UpjtGmjjsdS8Vob:-KgF1UpjtGmjjsdS8Voc:b1ui8y) ([raw file](https://github.com/hackerexperience/helix/blob/6e36cb6e3ad2a57c6b671eac5623a6877038b4cb/apps/helix_account/test/controller/account_test.exs#L161)):*
> ```Elixir
>         :setting
>         |> Factory.build()
>         |> Map.from_struct()
> ```

Hmm, i don't know if this is any better, maybe I could create the map more explicitly :S 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/37)*

**Comment by mememori** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks broke.

---

*[apps/helix_account/lib/account/model/setting.ex, line 11 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/37#-Kg0kqbW20G1bZfRajMs:-KgFLAylAbVOHpk3oXtC:b-mbpiwh) ([raw file](https://github.com/hackerexperience/helix/blob/88a3f3ce688637bce5d17eaa9c9da96f3318059c/apps/helix_account/lib/account/model/setting.ex#L11)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Follow our convention

---

*[apps/helix_account/lib/account/model/setting.ex, line 23 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/37#-KgFLIlzqLR3yXh1NUuD:-KgFLIlzqLR3yXh1NUuE:bmxtw6b) ([raw file](https://github.com/hackerexperience/helix/blob/6e36cb6e3ad2a57c6b671eac5623a6877038b4cb/apps/helix_account/lib/account/model/setting.ex#L23)):*
> ```Elixir
>   @spec default :: Setting.t
>   def default do
>     %__MODULE__{}
> ```

Remove this function

---

*[apps/helix_account/test/controller/account_test.exs, line 161 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/37#-KgF1UpjtGmjjsdS8Vob:-KgFLNb2sioBG83dS50p:b-qlsgwi) ([raw file](https://github.com/hackerexperience/helix/blob/6e36cb6e3ad2a57c6b671eac5623a6877038b4cb/apps/helix_account/test/controller/account_test.exs#L161)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Hmm, i don't know if this is any better, maybe I could create the map more explicitly :S 
</blockquote></details>

You shouldn't use a factory to produce parameters for your test. You should use fixtures or property-based testing.

As i said in the discussion on the previous line you had here, avoid using ExMachina to give you params as it is not suited to do that

---

*[apps/helix_account/test/support/factory.ex, line 27 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/37#-KgFLyhPKVwCa2HnlkqA:-KgFLyhPKVwCa2HnlkqB:b-u5xx97) ([raw file](https://github.com/hackerexperience/helix/blob/6e36cb6e3ad2a57c6b671eac5623a6877038b4cb/apps/helix_account/test/support/factory.ex#L27)):*
> ```Elixir
>       :setting
>       |> build()
>       |> Map.from_struct()
> ```

??????????????????????????????

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/37)*

**Comment by kress95** [comment]
Review status: 9 of 11 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[apps/helix_account/lib/account/model/setting.ex, line 23 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/37#-KgFLIlzqLR3yXh1NUuD:-KgGQIoG4WXv87rzJOmy:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/6e36cb6e3ad2a57c6b671eac5623a6877038b4cb/apps/helix_account/lib/account/model/setting.ex#L23)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

Remove this function
</blockquote></details>

Done.

---

*[apps/helix_account/test/support/factory.ex, line 27 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/37#-KgFLyhPKVwCa2HnlkqA:-KgGQvHUjTGNoymRbTeK:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/6e36cb6e3ad2a57c6b671eac5623a6877038b4cb/apps/helix_account/test/support/factory.ex#L27)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

??????????????????????????????
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/37)*

**Comment by kress95** [comment]
Passed through this before sending:
```
mix clean && mix compile && mix dialyzer && mix credo --strict && mix test
```

**Comment by mememori** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/37#-:-KgHds4CAKEvq01kaHne:bnfp4nl)*

**Comment by mememori** [comment]
Reviewed 2 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/37)*

**Pull request merged**
