### PR TITLE
Add Hardware API

### PR DESCRIPTION
**Pull request by kress95**
Welp, I'm tired :sweat_smile: 

This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/helix/93)

### CODE REVIEW

**Comment by kress95** [comment]
Weird, I tested everything beforehand, I'm fixing then.

**Comment by mememori** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[apps/helix_hardware/lib/hardware/controller/motherboard_slot.ex, line 33 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_vnWyG-WpsI1zQbSr:-Kg_vnWyG-WpsI1zQbSs:b6mx2gs) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/lib/hardware/controller/motherboard_slot.ex#L33)):*
> ```Elixir
>     update(slot, %{link_component_id: nil})
>   end
> end
> ```

much better :+1:

---

*[apps/helix_hardware/lib/hardware/model/motherboard_slot.ex, line 71 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_vrN0whtrxhyYezmz:-Kg_vrN0whtrxhyYezn-:bvd4sla) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/lib/hardware/model/motherboard_slot.ex#L71)):*
> ```Elixir
>   def update_changeset(struct, params) do
>     struct
>     |> changeset(params)
> ```

why piping when you have a single statement ?

---

*[apps/helix_hardware/lib/hardware/model/motherboard_slot.ex, line 97 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_vylyTY4Wv_fG1rt0:-Kg_vylyTY4Wv_fG1rt1:bmckmuh) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/lib/hardware/model/motherboard_slot.ex#L97)):*
> ```Elixir
>       add_error(changeset, :link_component_id, "component already attached")
>     end
>   end
> ```

overly hard to read, message does not follow our changeset error message format etc, check the other review

---

*[apps/helix_hardware/lib/hardware/service/api/component.ex, line 32 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_wNaaxhNzvWZDcDFR:-Kg_wNaaxhNzvWZDcDFS:blv0c08) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/lib/hardware/service/api/component.ex#L32)):*
> ```Elixir
> 
>     * `:id` - filters by ids within a list
>     * `:type` - filters by specification type or list
> ```

those descriptions are the opposite of clear, specially the last one, i have no idea what it means

---

*[apps/helix_hardware/lib/hardware/service/api/motherboard.ex, line 18 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kga0dKsEmB-MTagjfit:-Kga0dKsEmB-MTagjfiu:bvzlwb4) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/lib/hardware/service/api/motherboard.ex#L18)):*
> ```Elixir
>   def create_from_spec(component_spec) do
>     MotherboardController.create_from_spec(component_spec)
>   end
> ```

I'm not sure why on the internal API we have the `create_from_spec` function on both the Motherboard controller and on the Component controller.

Remove it as it is completely redundant

---

*[apps/helix_hardware/lib/hardware/service/api/motherboard.ex, line 66 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kga0gA1mlsrzkFbBjSC:-Kga0gA1mlsrzkFbBjSD:b4tztox) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/lib/hardware/service/api/motherboard.ex#L66)):*
> ```Elixir
>   def unlink_components_from_motherboard(motherboard) do
>     MotherboardController.unlink_components_from_motherboard(motherboard)
>   end
> ```

I don't really think this function should exist in the API. It was created for a single reason: sanity check before detaching a motherboard from a server.

So, tl;dr, this function should only be used on a single point: on the event `%MotherboardDetached{}`

---

*[apps/helix_hardware/lib/hardware/service/api/motherboard.ex, line 70 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_xcnik6GmT0Jkqcox:-Kg_xcnik6GmT0Jkqcoy:b-igv8o) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/lib/hardware/service/api/motherboard.ex#L70)):*
> ```Elixir
>   @spec delete(Motherboard.t | HELL.PK.t) :: no_return
>   @doc """
>   Deletes the motherboard, unlinking every linked components
> ```

that it unlinks every component attached to it as not the definition of the function but a detail on what it does

---

*[apps/helix_hardware/lib/ws/routes.ex, line 13 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_xlqjEDdygBvRtUrv:-Kg_xlqjEDdygBvRtUrw:b5igfso) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/lib/ws/routes.ex#L13)):*
> ```Elixir
>     end)
>   end
> end
> ```

erm okay i guess ?

---

*[apps/helix_hardware/test/service/api/component_spec_test.exs, line 6 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_xsubQkQ3bs1vGVXD:-Kg_xsubQkQ3bs1vGVXE:brgo7hh) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/test/service/api/component_spec_test.exs#L6)):*
> ```Elixir
> 
>   alias HELL.TestHelper.Random
>   alias Helix.Hardware.Controller.ComponentSpec, as: API
> ```

Controller as API ? Why ? This alone invalidates the whole test case and thus i won't even check if it is correct

---

*[apps/helix_hardware/test/service/api/component_test.exs, line 17 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_yGy7LaP6FgGXlGbp:-Kg_y5kSXRw9OQVCTVdb:b8v3pnq) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/test/service/api/component_test.exs#L17)):*
> ```Elixir
>     defp random_spec do
>       Enum.random([:cpu_spec, :hdd_spec, :nic_spec, :ram_spec])
>     end
> ```

Why did you add this function on this scope ? Remove it and don't depend on those factory generators because in the near future i'll remove them all

---

*[apps/helix_hardware/test/service/api/component_test.exs, line 20 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_yCYBKoyKdlPlozBY:-Kg_yCYBKoyKdlPlozBZ:brz6qxv) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/test/service/api/component_test.exs#L20)):*
> ```Elixir
> 
>     test "succeeds with valid input" do
>       spec = Factory.insert(random_spec())
> ```

If you're gonna do this, why don't you let the factory randomly give you a certain spec ?

---

*[apps/helix_hardware/test/service/api/component_test.exs, line 24 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_yZ1jCpZzhtc21JxW:-Kg_yZ1kc4mDBpIpFZNV:b-a3cqjb) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/test/service/api/component_test.exs#L24)):*
> ```Elixir
>     end
> 
>     test "returns changeset when input is invalid" do
> ```

I'd prefer if you kept using the "fails when" style as this makes it unobvious if the operation is succeeding or not specially since there are cases that you might want to return the changeset for further transformation

---

*[apps/helix_hardware/test/service/api/component_test.exs, line 26 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_yXVPyJDPezGSY7IT:-Kg_yXVPyJDPezGSY7IU:bjquptk) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/test/service/api/component_test.exs#L26)):*
> ```Elixir
>     test "returns changeset when input is invalid" do
>       bogus_spec = Factory.build(random_spec())
>       assert {:error, %Ecto.Changeset{}} = API.create_from_spec(bogus_spec)
> ```

same as before

---

*[apps/helix_hardware/test/service/api/component_test.exs, line 36 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_zCXnLjvlGo0YsphF:-Kg_zCXnLjvlGo0YsphG:b2ngvnt) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/test/service/api/component_test.exs#L36)):*
> ```Elixir
>     end
> 
>     test "fails with inexistent id" do
> ```

...

---

*[apps/helix_hardware/test/service/api/component_test.exs, line 108 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_zYtPL0KUPTLdS_VE:-Kg_zYtPL0KUPTLdS_VF:bfpy3lr) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/test/service/api/component_test.exs#L108)):*
> ```Elixir
>       API.delete(component.component_id)
> 
>       refute Repo.get(Component, component.component_id)
> ```

this format is not cool. Do either

```elixir
assert

delete

refute
```

or

```elixir
assert
delete
refute
```

---

*[apps/helix_hardware/test/service/api/motherboard_test.exs, line 122 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kga-__lW3t5vfIfDYMD:-Kga-__lW3t5vfIfDYME:b-wppno7) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/test/service/api/motherboard_test.exs#L122)):*
> ```Elixir
>       {:ok, slot} = API.link(slot, component1.component)
> 
>       assert {:error, %Ecto.Changeset{}} = API.link(slot, component2.component)
> ```

check if the changeset is valid

---

*[apps/helix_hardware/test/service/api/motherboard_test.exs, line 138 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kga-hsV6_WkONkyHB8v:-Kga-hsV6_WkONkyHB8w:b-wppno7) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/test/service/api/motherboard_test.exs#L138)):*
> ```Elixir
>       API.link(slot1, component.component)
> 
>       assert {:error, %Ecto.Changeset{}} = API.link(slot2, component.component)
> ```

check if the changeset is valid

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/93)*

**Comment by kress95** [comment]
*[apps/helix_hardware/lib/hardware/service/api/component.ex, line 32 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_wNaaxhNzvWZDcDFR:-KgaOJ8OuTlbbZlLwpgo:bko7evs) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/lib/hardware/service/api/component.ex#L32)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

those descriptions are the opposite of clear, specially the last one, i have no idea what it means
</blockquote></details>

please, for such cases of obvious problems ~~(the ones that have a great range of not so obvious best solutions)~~, give an example to be used as a template

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/93)*

**Comment by kress95** [comment]
*[apps/helix_hardware/test/service/api/component_spec_test.exs, line 6 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_xsubQkQ3bs1vGVXD:-KgaRCYHQohcSO949-l_:b-famdps) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/test/service/api/component_spec_test.exs#L6)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

Controller as API ? Why ? This alone invalidates the whole test case and thus i won't even check if it is correct
</blockquote></details>

wth, something went relly wrong here, but I'm 99% sure the tests will still pass after changing the alias :v

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/93)*

**Comment by kress95** [comment]
*[apps/helix_hardware/test/service/api/component_test.exs, line 24 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_yZ1jCpZzhtc21JxW:-KgaSSN5wbG-nvXCRIuG:b-l97u6j) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/test/service/api/component_test.exs#L24)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

I'd prefer if you kept using the "fails when" style as this makes it unobvious if the operation is succeeding or not specially since there are cases that you might want to return the changeset for further transformation
</blockquote></details>

pls document that somewhere so we're able get a consistent style across tests, tha lack of it always make changing test descriptions a struggle to me

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/93)*

**Comment by kress95** [comment]
*[apps/helix_hardware/test/service/api/component_spec_test.exs, line 6 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_xsubQkQ3bs1vGVXD:-KgaTARzeGZdowa4pB_Y:b-oo0w07) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/test/service/api/component_spec_test.exs#L6)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

wth, something went relly wrong here, but I'm 99% sure the tests will still pass after changing the alias :v
</blockquote></details>

Yeah, I was right, currently these tests could even be a complete copy pasta since there's no henforcer, but I want to make it right...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/93)*

**Comment by kress95** [comment]
Review status: 7 of 13 files reviewed at latest revision, 16 unresolved discussions.

---

*[apps/helix_hardware/lib/hardware/model/motherboard_slot.ex, line 71 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_vrN0whtrxhyYezmz:-KgaNqQU2qLmjw20anva:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/lib/hardware/model/motherboard_slot.ex#L71)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

why piping when you have a single statement ?
</blockquote></details>

Done.

---

*[apps/helix_hardware/lib/hardware/model/motherboard_slot.ex, line 97 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_vylyTY4Wv_fG1rt0:-KgaNpLZ0XTZ-zLMXNK1:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/lib/hardware/model/motherboard_slot.ex#L97)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

overly hard to read, message does not follow our changeset error message format etc, check the other review
</blockquote></details>

Done.

---

*[apps/helix_hardware/lib/hardware/service/api/motherboard.ex, line 18 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kga0dKsEmB-MTagjfit:-KgaX44XqiTmbF0XJ5kl:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/lib/hardware/service/api/motherboard.ex#L18)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

I'm not sure why on the internal API we have the `create_from_spec` function on both the Motherboard controller and on the Component controller.

Remove it as it is completely redundant
</blockquote></details>

Done.

---

*[apps/helix_hardware/lib/hardware/service/api/motherboard.ex, line 66 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kga0gA1mlsrzkFbBjSC:-KgaQxiL-DJdMQN83mmW:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/lib/hardware/service/api/motherboard.ex#L66)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

I don't really think this function should exist in the API. It was created for a single reason: sanity check before detaching a motherboard from a server.

So, tl;dr, this function should only be used on a single point: on the event `%MotherboardDetached{}`
</blockquote></details>

Done.

---

*[apps/helix_hardware/lib/hardware/service/api/motherboard.ex, line 70 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_xcnik6GmT0Jkqcox:-KgaQwSr70WZ6q96b7XH:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/lib/hardware/service/api/motherboard.ex#L70)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

that it unlinks every component attached to it as not the definition of the function but a detail on what it does
</blockquote></details>

Done.

---

*[apps/helix_hardware/lib/ws/routes.ex, line 13 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_xlqjEDdygBvRtUrv:-KgaR-StEsbe2RupKjq7:b2qyp64) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/lib/ws/routes.ex#L13)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

erm okay i guess ?
</blockquote></details>

~~I have no idea about what I'm doing :upside_down_face: ~~
I don't know what to add here

---

*[apps/helix_hardware/test/service/api/component_spec_test.exs, line 6 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_xsubQkQ3bs1vGVXD:-KgaY9wDJo2OeWwPbgOL:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/test/service/api/component_spec_test.exs#L6)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Yeah, I was right, currently these tests could even be a complete copy pasta since there's no henforcer, but I want to make it right...
</blockquote></details>

Done.

---

*[apps/helix_hardware/test/service/api/component_test.exs, line 17 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_yGy7LaP6FgGXlGbp:-KgaU1IUYTEmGdNdKqAQ:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/test/service/api/component_test.exs#L17)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

Why did you add this function on this scope ? Remove it and don't depend on those factory generators because in the near future i'll remove them all
</blockquote></details>

Done.

---

*[apps/helix_hardware/test/service/api/component_test.exs, line 20 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_yCYBKoyKdlPlozBY:-KgaUxSR0B6PolPWx2JJ:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/test/service/api/component_test.exs#L20)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

If you're gonna do this, why don't you let the factory randomly give you a certain spec ?
</blockquote></details>

Done.

---

*[apps/helix_hardware/test/service/api/component_test.exs, line 24 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_yZ1jCpZzhtc21JxW:-KgaY8LnRE42cFCpVhKm:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/test/service/api/component_test.exs#L24)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

pls document that somewhere so we're able get a consistent style across tests, tha lack of it always make changing test descriptions a struggle to me
</blockquote></details>

Done.

---

*[apps/helix_hardware/test/service/api/component_test.exs, line 26 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_yXVPyJDPezGSY7IT:-KgaW5_YRsisEBVcZYXo:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/test/service/api/component_test.exs#L26)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

same as before
</blockquote></details>

Done.

---

*[apps/helix_hardware/test/service/api/component_test.exs, line 36 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_zCXnLjvlGo0YsphF:-KgaW9vg2ll0J1LBNjj8:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/test/service/api/component_test.exs#L36)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

...
</blockquote></details>

Done.

---

*[apps/helix_hardware/test/service/api/component_test.exs, line 108 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_zYtPL0KUPTLdS_VE:-KgaWiTedThkQ8Ntpw9u:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/test/service/api/component_test.exs#L108)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

this format is not cool. Do either

```elixir
assert

delete

refute
```

or

```elixir
assert
delete
refute
```
</blockquote></details>

Done.

---

*[apps/helix_hardware/test/service/api/motherboard_test.exs, line 122 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kga-__lW3t5vfIfDYMD:-KgaVJBpBM8Ugcj25411:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/test/service/api/motherboard_test.exs#L122)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

check if the changeset is valid
</blockquote></details>

Done.

---

*[apps/helix_hardware/test/service/api/motherboard_test.exs, line 138 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kga-hsV6_WkONkyHB8v:-KgaVJcWzjnaw9ZomhWc:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/test/service/api/motherboard_test.exs#L138)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

check if the changeset is valid
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/93)*

**Comment by kress95** [comment]
*[apps/helix_hardware/lib/hardware/service/api/component.ex, line 32 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_wNaaxhNzvWZDcDFR:-Kga_6Zr8ud3yitjVbdI:b-ey14fp) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/lib/hardware/service/api/component.ex#L32)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

please, for such cases of obvious problems ~~(the ones that have a great range of not so obvious best solutions)~~, give an example to be used as a template
</blockquote></details>

Not sure if it's right, but I tried.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/93)*

**Comment by mememori** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[apps/helix_hardware/lib/hardware/service/api/component.ex, line 32 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_wNaaxhNzvWZDcDFR:-KgaejYERPWyoLD5Tdls:b-lrwqxu) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/lib/hardware/service/api/component.ex#L32)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Not sure if it's right, but I tried.
</blockquote></details>

Better but i have no idea how i use it. "search for component ids". Ok, so i should use it as `find(:id)` ?

---

*[apps/helix_hardware/lib/hardware/service/api/motherboard.ex, line 70 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/93#-Kg_xcnik6GmT0Jkqcox:-KgaexGjBJVxPdDehREz:b-m6gobu) ([raw file](https://github.com/hackerexperience/helix/blob/37e813dab5dbce51a2ab0fb4eb6cc9d6f41e5eb5/apps/helix_hardware/lib/hardware/service/api/motherboard.ex#L70)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Better but i would make it as a separate paragraph from the idempotency part

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/93#-:-KgafxFRE-U1-ciLifAH:bnfp4nl)*

**Comment by mememori** [comment]
OTP
:shipit: **lgtm** :shipit:

**Pull request merged**
