### PR TITLE
Add coveralls support

### PR DESCRIPTION
**Pull request by renatomassaro**
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/helix/205)

### CODE REVIEW

**Comment by GabrielAugustoTI** [comment]
@renatomassaro please tell with community!

**Comment by renatomassaro** [comment]
I'll leave this PR on hold for a while because Coverall's api is slow and with some downtime. Their status page: http://status.coveralls.io/

**Comment by renatomassaro** [comment]
@GabrielAugustoTI I will, wait a little bit more plz.

**Comment by GabrielAugustoTI** [comment]
I only have 6 questions for you:

Will the HE1 legacy never become open source?
Why HEBorn was not released on 07/08?
Is there a problem with my project to rewrite the HE1 Legacy backend?
Why was the promise of better communication with the community forgotten?
When are you going to hire a community manager?
Will HE2 really be released?

**Comment by renatomassaro** [comment]
> Will the HE1 legacy never become open source?

I'm open (no pun intended) to it. See https://github.com/HECommunity/HELegacy/issues/2

> Why HEBorn was not released on 07/08?

Problems.

> Is there a problem with my project to rewrite the HE1 Legacy backend?

Other than the domain name, none at all. I'd actually like to help however I can.

> Why was the promise of better communication with the community forgotten?

Problems, no time etc. The usual excuses.

> When are you going to hire a community manager?

Whenever I have the money for it.

> Will HE2 really be released?

No, we are just completely wasting our time here and will delete the whole repository as soon as we finish the project.

**Pull request merged**
