### PR TITLE
FileText as a File specialization

### PR DESCRIPTION
**Pull request by kress95**
It should be okay now :smile: 

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/helix/149)

### CODE REVIEW

**Comment by kress95** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[lib/software/model/file_text.ex, line 41 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/149#-Kh8Tlou9KVhSRNnfcIX:-Kh8Tlou9KVhSRNnfcIY:bu5uwtn) ([raw file](https://github.com/hackerexperience/helix/blob/789c0847b1742ccdba3054c12457a5b3a342f044/lib/software/model/file_text.ex#L41)):*
> ```Elixir
>   @spec create(Storage.t, creation_params) ::
>     Ecto.Changeset.t
>   def create(storage = %Storage{}, params) do
> ```

I'm accepting a map here, but I don't know if it's ideal.

---

*[lib/software/model/file_text.ex, line 73 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/149#-Kh8TvD8pNKowGYU8wyc:-Kh8TvD8pNKowGYU8wyd:b-jbah3a) ([raw file](https://github.com/hackerexperience/helix/blob/789c0847b1742ccdba3054c12457a5b3a342f044/lib/software/model/file_text.ex#L73)):*
> ```Elixir
>       |> Map.put(:software_type, @software_type)
> 
>     File.create(storage, params)
> ```

I'm leaving the part of describing file's name/file to params, but maybe it should be automatically generated like crypto keys.

---

*[lib/software/model/software_type.ex, line 26 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/149#-Kh8U6AGTXH39w-HS_tc:-Kh8U6AGTXH39w-HS_td:b-iyp1og) ([raw file](https://github.com/hackerexperience/helix/blob/789c0847b1742ccdba3054c12457a5b3a342f044/lib/software/model/software_type.ex#L26)):*
> ```Elixir
>         extension: "txt",
>         modules: []
>       },
> ```

This was the most logical choice for me, but "text" being a software bugs me so much.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/149)*

**Comment by kress95** [comment]
@mememori may you give me some insights for the raised concerns? :smiley:

**Comment by mememori** [comment]
Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[lib/software/controller/file_text.ex, line 24 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/149#-KhGQQfTYcjDrN0NA0kq:-KhGQQfTYcjDrN0NA0kr:b-wv2fgt) ([raw file](https://github.com/hackerexperience/helix/blob/2f5ef1ad750eee5e11b831db53c9314a51035fb6/lib/software/controller/file_text.ex#L24)):*
> ```Elixir
>     |> FileText.Query.from_file()
>     |> Repo.one()
>   end
> ```

Why didn't you follow CryptoKey's format ?

---

*[lib/software/model/file_text.ex, line 41 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/149#-Kh8Tlou9KVhSRNnfcIX:-KhGQUkIzIvofEi3cH3S:b-8azrqd) ([raw file](https://github.com/hackerexperience/helix/blob/789c0847b1742ccdba3054c12457a5b3a342f044/lib/software/model/file_text.ex#L41)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

I'm accepting a map here, but I don't know if it's ideal.
</blockquote></details>

I'd prefer to make it as explicit as possible: `name`, `path` and `contents`

---

*[lib/software/model/file_text.ex, line 73 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/149#-Kh8TvD8pNKowGYU8wyc:-KhGQgDQY5OjB79qn-KZ:b-prilrn) ([raw file](https://github.com/hackerexperience/helix/blob/789c0847b1742ccdba3054c12457a5b3a342f044/lib/software/model/file_text.ex#L73)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

I'm leaving the part of describing file's name/file to params, but maybe it should be automatically generated like crypto keys.
</blockquote></details>

this is okay

---

*[lib/software/model/file_text.ex, line 43 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/149#-KhGQ_LDCfm1HX9Wr_ae:-KhGQ_LDCfm1HX9Wr_af:b-7h97ni) ([raw file](https://github.com/hackerexperience/helix/blob/2f5ef1ad750eee5e11b831db53c9314a51035fb6/lib/software/model/file_text.ex#L43)):*
> ```Elixir
>   def create(storage = %Storage{}, params) do
>     file = generate_file(storage, params)
>     params = Map.take(params, [:contents])
> ```

why ?

---

*[lib/software/model/software_type.ex, line 26 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/149#-Kh8U6AGTXH39w-HS_tc:-KhGQEPp5ELscuF3WvrU:bb6mt9b) ([raw file](https://github.com/hackerexperience/helix/blob/789c0847b1742ccdba3054c12457a5b3a342f044/lib/software/model/software_type.ex#L26)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

This was the most logical choice for me, but "text" being a software bugs me so much.
</blockquote></details>

:+1:

---

*[test/software/controller/file_text_test.exs, line 44 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/149#-KhGQn3sh9hWoRbYQH8W:-KhGQn3sh9hWoRbYQH8X:b32wsm) ([raw file](https://github.com/hackerexperience/helix/blob/2f5ef1ad750eee5e11b831db53c9314a51035fb6/test/software/controller/file_text_test.exs#L44)):*
> ```Elixir
>     test "fails when file_text doesn't exist" do
>       refute FileTextController.fetch(Random.pk())
>     end
> ```

no

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/149)*

**Comment by kress95** [comment]
Review status: 1 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/hackerexperience/helix/149#-KhNjjPEy5JDsXPVCPGS:-KhNjjPEy5JDsXPVCPGT:b-6l4shq) (no related file):*
Quick question, why it's called `FileText` instead of `Text` or just `TextFile`?
Also, there's any relationship between `FileText`s and logs?

---

*[lib/software/controller/file_text.ex, line 24 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/149#-KhGQQfTYcjDrN0NA0kq:-KhNcG92L0sYFrP2t1jS:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/19626d88fd5a05911436db0f676a6778768fdfcc/lib/software/controller/file_text.ex#L24)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

Why didn't you follow CryptoKey's format ?
</blockquote></details>

Done.

---

*[lib/software/model/file_text.ex, line 41 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/149#-Kh8Tlou9KVhSRNnfcIX:-KhNbakMLudKoXv9bi29:bnsnqra) ([raw file](https://github.com/hackerexperience/helix/blob/789c0847b1742ccdba3054c12457a5b3a342f044/lib/software/model/file_text.ex#L41)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

I'd prefer to make it as explicit as possible: `name`, `path` and `contents`
</blockquote></details>

I was going to use explicit params, but I couldn't decide the param ordering, this is why it ended up as a map.

---

*[lib/software/model/file_text.ex, line 43 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/149#-KhGQ_LDCfm1HX9Wr_ae:-KhNd4HUI5XZERZS99VQ:brv850p) ([raw file](https://github.com/hackerexperience/helix/blob/19626d88fd5a05911436db0f676a6778768fdfcc/lib/software/model/file_text.ex#L43)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

why ?
</blockquote></details>

I think it's better now.

---

*[test/software/controller/file_text_test.exs, line 44 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/149#-KhGQn3sh9hWoRbYQH8W:-KhNjSPX74LvHcaTtA6a:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/19626d88fd5a05911436db0f676a6778768fdfcc/test/software/controller/file_text_test.exs#L44)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

no
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/149)*

**Comment by kress95** [comment]
I wanted to move this one to review, but it seems I can't.

**Comment by mememori** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/hackerexperience/helix/149#-KhNjjPEy5JDsXPVCPGS:-KhOtrzPGDB0NNZJUlOC:b-c1i1mh) (no related file):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Quick question, why it's called `FileText` instead of `Text` or just `TextFile`?
Also, there's any relationship between `FileText`s and logs?
</blockquote></details>

I'd prefer for it to be `TextFile`. If i am not mistaken, who gave the name `FileText` was you. `Text` is not good because it can be anything (and AFAIK `text` is a reserved keyword)

And no, there's no relationship between it and logs

---

*[lib/software/controller/file_text.ex, line 14 at r3](https://reviewable.io:443/reviews/hackerexperience/helix/149#-KhON_87RWKzKU_MnUO9:-KhON_88rFrCbdsAjJuM:bubcpjs) ([raw file](https://github.com/hackerexperience/helix/blob/a1a5711b68fdab4dc263bc400a6aadc828650ae3/lib/software/controller/file_text.ex#L14)):*
> ```Elixir
>   Creates a `file text` on `storage`
>   """
>   def create(storage, name, path, contents \\ "") do
> ```

why default the contents ?

An empty text may be created, okay, but the client has to say "content is an empty string"

---

*[lib/software/model/file_text.ex, line 44 at r3](https://reviewable.io:443/reviews/hackerexperience/helix/149#-KhONo4VKEycTz7KJlDE:-KhONo4VKEycTz7KJlDF:b-uz67rx) ([raw file](https://github.com/hackerexperience/helix/blob/a1a5711b68fdab4dc263bc400a6aadc828650ae3/lib/software/model/file_text.ex#L44)):*
> ```Elixir
>   Creates a `file text`  on `storage`.
>   """
>   def create(storage = %Storage{}, name, path, contents \\ "") do
> ```

same problem as the controller

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/149)*

**Comment by mememori** [comment]
Remove the defaults as they are meaningless and it's ready to land

**Comment by kress95** [comment]
> If i am not mistaken, who gave the name FileText was you. 

Kinda yes, but the name came from a [data model](http://imgur.com/a/wDEiu).

**Comment by kress95** [comment]
Defaults removed.

---

Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/hackerexperience/helix/149#-KhNjjPEy5JDsXPVCPGS:-KhSh0QuZ-9LGoaWwKeQ:b2uynd5) (no related file):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

I'd prefer for it to be `TextFile`. If i am not mistaken, who gave the name `FileText` was you. `Text` is not good because it can be anything (and AFAIK `text` is a reserved keyword)

And no, there's no relationship between it and logs
</blockquote></details>

Thanks for clearing that about the logs.

I've done the rename on [another branch](https://github.com/kress95/Helix/tree/file-text-to-text-file), as it looked fast to do it, I'll PR if you like it.

By the way, I'm context switching to HEBornMigration now.

---

*[lib/software/controller/file_text.ex, line 14 at r3](https://reviewable.io:443/reviews/hackerexperience/helix/149#-KhON_87RWKzKU_MnUO9:-KhSh4JIy1m7MjnuPWDo:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/a1a5711b68fdab4dc263bc400a6aadc828650ae3/lib/software/controller/file_text.ex#L14)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

why default the contents ?

An empty text may be created, okay, but the client has to say "content is an empty string"
</blockquote></details>

Done.

---

*[lib/software/model/file_text.ex, line 44 at r3](https://reviewable.io:443/reviews/hackerexperience/helix/149#-KhONo4VKEycTz7KJlDE:-KhSh4sglnL2EpcPhey-:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/a1a5711b68fdab4dc263bc400a6aadc828650ae3/lib/software/model/file_text.ex#L44)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

same problem as the controller
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/149#-:-KhShyrTvrWToe80K50f:bye8evr)*

**Comment by mememori** [comment]
If you did it, PR it. Otherwise just don't waste time doing such things

**Comment by mememori** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/149#-:-KhSkZN1NHhkDdyNwaN-:bnfp4nl)*

**Pull request merged**
