### PR TITLE
Update process fetch find

### PR DESCRIPTION
**Pull request by kress95**
No tests added, but I tried.
Everything looks okay aside from that.

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/helix/74)

### CODE REVIEW

**Comment by kress95** [comment]
Done locally, I'll update the branch once #77 gets merged.

**Comment by kress95** [comment]
Reason for not updating descriptions:

No update were done for controller test descriptions (at least until now), so I'm assuming this should be delayed.
Also, I'm not 100% sure about which format they should have, we don't have any documentation for that conventions.

**Comment by mememori** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks broke.

---

*[apps/helix_process/lib/process/model/process.ex, line 462 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/74#-Kg_p1I1tqGvM-bw2sw4:-Kg_p1I1tqGvM-bw2sw5:b-q30yy6) ([raw file](https://github.com/hackerexperience/helix/blob/4c308f64feb584645f7b9cf4fcf9f5b55caaeea1/apps/helix_process/lib/process/model/process.ex#L462)):*
> ```Elixir
>       do: where(query, [p], p.process_type in ^type_list)
> 
>     @spec from_state_list(Ecto.Queryable.t, [State.t]) :: Ecto.Queryable.t
> ```

type `State.t` doesn't exists

---

*[apps/helix_process/priv/repo/migrations/20170329222422_add_process_data.exs, line 7 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/74#-Kg_p9I9scLmHh-DV0ZA:-Kg_p9I9scLmHh-DV0ZB:b-2grp4n) ([raw file](https://github.com/hackerexperience/helix/blob/4c308f64feb584645f7b9cf4fcf9f5b55caaeea1/apps/helix_process/priv/repo/migrations/20170329222422_add_process_data.exs#L7)):*
> ```Elixir
>     alter table(:processes) do
>       add :process_data, :jsonb,
>         null: false
> ```

same line

---

*[apps/helix_process/test/controller/process_test.exs, line 30 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/74#-Kg_pH1KJxL-OxmStGe8:-Kg_pH1KJxL-OxmStGe9:b-dsxewg) ([raw file](https://github.com/hackerexperience/helix/blob/4c308f64feb584645f7b9cf4fcf9f5b55caaeea1/apps/helix_process/test/controller/process_test.exs#L30)):*
> ```Elixir
>     end
> 
>     test "fails when process with id doesn't exist" do
> ```

process doesn't exists

---

*[apps/helix_process/test/support/factory.ex, line 12 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/74#-Kg_pq8z1H5OSpEhYLqa:-Kg_pq8z1H5OSpEhYLqb:bdj6dfj) ([raw file](https://github.com/hackerexperience/helix/blob/4c308f64feb584645f7b9cf4fcf9f5b55caaeea1/apps/helix_process/test/support/factory.ex#L12)):*
> ```Elixir
>   alias HELL.TestHelper.Random
> 
>   defmodule NaiveProcessType do
> ```

bad module name

---

*[apps/helix_process/test/support/factory.ex, line 22 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/74#-Kg_pnE6y9NSs7lNz4OM:-Kg_pnE6y9NSs7lNz4ON:borgfme) ([raw file](https://github.com/hackerexperience/helix/blob/4c308f64feb584645f7b9cf4fcf9f5b55caaeea1/apps/helix_process/test/support/factory.ex#L22)):*
> ```Elixir
>     def event_namespace(_),
>       do: nil
>   end
> ```

this is not compatible with master

---

*[apps/helix_process/test/support/factory.ex, line 33 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/74#-Kg_pyms7NIVLKdvF7F3:-Kg_pyms7NIVLKdvF7F4:b-fkcia7) ([raw file](https://github.com/hackerexperience/helix/blob/4c308f64feb584645f7b9cf4fcf9f5b55caaeea1/apps/helix_process/test/support/factory.ex#L33)):*
> ```Elixir
> 
>     build(:resources, params)
>   end
> ```

why this instead of simply `%Resources{cpu: Random.number(0..1024), ...}` ?

---

*[apps/helix_process/test/support/factory.ex, line 44 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/74#-Kg_q4iFF8oj3BSyQeZ2:-Kg_q4iFF8oj3BSyQeZ3:b-fkcia7) ([raw file](https://github.com/hackerexperience/helix/blob/4c308f64feb584645f7b9cf4fcf9f5b55caaeea1/apps/helix_process/test/support/factory.ex#L44)):*
> ```Elixir
> 
>     build(:resources, params)
>   end
> ```

why this instead of simply `%Resources{cpu: Random.number(0..1024), ...}` ?

---

*[apps/helix_process/test/support/factory.ex, line 75 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/74#-Kg_qPRhiWzwD5MZnNGX:-Kg_qPRhiWzwD5MZnNGY:b-64zca5) ([raw file](https://github.com/hackerexperience/helix/blob/4c308f64feb584645f7b9cf4fcf9f5b55caaeea1/apps/helix_process/test/support/factory.ex#L75)):*
> ```Elixir
>       ulk: Random.number(4096..8192)
>     }
>   end
> ```

No, this is not a db record, i'd prefer that you didn't try to provide a `insert` method for it

---

*[apps/helix_process/test/support/factory.ex, line 84 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/74#-Kg_qVKfQdRZf34CD1N4:-Kg_qVKfQdRZf34CD1N5:b-64zca5) ([raw file](https://github.com/hackerexperience/helix/blob/4c308f64feb584645f7b9cf4fcf9f5b55caaeea1/apps/helix_process/test/support/factory.ex#L84)):*
> ```Elixir
>       ulk: nil
>     }
>   end
> ```

No, this is not a db record, i'd prefer that you didn't try to provide a `insert` method for it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/74)*

**Comment by kress95** [comment]
Review status: 2 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[apps/helix_process/lib/process/model/process.ex, line 462 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/74#-Kg_p1I1tqGvM-bw2sw4:-KgabQ5GY6QEAFlFUyPt:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/4c308f64feb584645f7b9cf4fcf9f5b55caaeea1/apps/helix_process/lib/process/model/process.ex#L462)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

type `State.t` doesn't exists
</blockquote></details>

Done.

---

*[apps/helix_process/priv/repo/migrations/20170329222422_add_process_data.exs, line 7 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/74#-Kg_p9I9scLmHh-DV0ZA:-KgacdCxIgzgvZjyU3Fg:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/4c308f64feb584645f7b9cf4fcf9f5b55caaeea1/apps/helix_process/priv/repo/migrations/20170329222422_add_process_data.exs#L7)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

same line
</blockquote></details>

Done.

---

*[apps/helix_process/test/controller/process_test.exs, line 30 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/74#-Kg_pH1KJxL-OxmStGe8:-Kgab_e4udoaJ3FtRY9y:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/4c308f64feb584645f7b9cf4fcf9f5b55caaeea1/apps/helix_process/test/controller/process_test.exs#L30)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

process doesn't exists
</blockquote></details>

Done.

---

*[apps/helix_process/test/support/factory.ex, line 12 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/74#-Kg_pq8z1H5OSpEhYLqa:-KgabhQCsLDC9XOmPDUF:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/4c308f64feb584645f7b9cf4fcf9f5b55caaeea1/apps/helix_process/test/support/factory.ex#L12)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

bad module name
</blockquote></details>

Done.

---

*[apps/helix_process/test/support/factory.ex, line 22 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/74#-Kg_pnE6y9NSs7lNz4OM:-KgacCgFaNk5xmMiyazb:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/4c308f64feb584645f7b9cf4fcf9f5b55caaeea1/apps/helix_process/test/support/factory.ex#L22)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

this is not compatible with master
</blockquote></details>

Done.

---

*[apps/helix_process/test/support/factory.ex, line 33 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/74#-Kg_pyms7NIVLKdvF7F3:-KgacN_NfpwNRsRPH2JW:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/4c308f64feb584645f7b9cf4fcf9f5b55caaeea1/apps/helix_process/test/support/factory.ex#L33)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

why this instead of simply `%Resources{cpu: Random.number(0..1024), ...}` ?
</blockquote></details>

Done.

---

*[apps/helix_process/test/support/factory.ex, line 44 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/74#-Kg_q4iFF8oj3BSyQeZ2:-KgacO9PTc8UElJdzW09:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/4c308f64feb584645f7b9cf4fcf9f5b55caaeea1/apps/helix_process/test/support/factory.ex#L44)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

why this instead of simply `%Resources{cpu: Random.number(0..1024), ...}` ?
</blockquote></details>

Done.

---

*[apps/helix_process/test/support/factory.ex, line 75 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/74#-Kg_qPRhiWzwD5MZnNGX:-KgacapokBNbGBElt734:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/4c308f64feb584645f7b9cf4fcf9f5b55caaeea1/apps/helix_process/test/support/factory.ex#L75)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

No, this is not a db record, i'd prefer that you didn't try to provide a `insert` method for it
</blockquote></details>

Done.

---

*[apps/helix_process/test/support/factory.ex, line 84 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/74#-Kg_qVKfQdRZf34CD1N4:-KgacbK4aZgoHOG1rzBD:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/4c308f64feb584645f7b9cf4fcf9f5b55caaeea1/apps/helix_process/test/support/factory.ex#L84)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

No, this is not a db record, i'd prefer that you didn't try to provide a `insert` method for it
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/74)*

**Comment by mememori** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 1 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[apps/helix_process/test/support/factory.ex, line 49 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/74#-KgahDaVrjwbDzFbNRL1:-KgahDaVrjwbDzFbNRL2:b6hntjo) ([raw file](https://github.com/hackerexperience/helix/blob/1fe0700dce04fe402f10961e4766194e2bf9953d/apps/helix_process/test/support/factory.ex#L49)):*
>   defp generate_processed do
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>
>     %Resources{
>       cpu: Random.number(0..1024),
>       ram: Random.number(0..1024),
>       dlk: Random.number(0..1024),
>       ulk: Random.number(0..1028)
>     }
</details>
>  
>  
>   end
>  
>   defp generate_allocated do
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>
>     %Resources{
>       cpu: Random.number(1024..2048),
>       ram: Random.number(1024..2048),
>       dlk: Random.number(1024..2048),
>       ulk: Random.number(1024..2048)
>     }
</details>
>   end
>  
>   defp generate_resources do
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>
>     %Resources{
>       cpu: Random.number(4096..8192),
>       ram: Random.number(4096..8192),
>       dlk: Random.number(4096..8192),
>       ulk: Random.number(4096..8192)
>     }
</details>
>   end
I disagree with the way this was solved but i'll let it be merged since i'll be updating the factories

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/74#-:-KgahPntfgvZs2QuaglU:bnfp4nl)*

**Pull request merged**
