### PR TITLE
Now you're thinking with channels

### PR DESCRIPTION
**Pull request by mememori**
- Implements Phoenix Channels
- Provides two different sockets: one that has access to public topics and one that has access to authenticated topics
- Implements authentication using channels
- Implements generic topics on a request-response cycle
- Implements way to push down messages to certain topics
- Replaces JWT with Session

There are a few things that still have to be considered before merging this to the main repo (and, after that, before merging it into master):

1) Is it adequate to have the client join a dozen of channels just to have access to certain events ? (every request is an event). Eg: have to join "account" channel/topic to ask `"account.get", %{account_id: 123}`
2) Will it be okay for the client part to use two different socket instances ? (i mean in the maintanability and obviousness aspect) because with two sockets we can clearly border out what requires authentication and what doesn't and don't need to add boilerplate checks on every topic
3) I really don't like how `1` is looking. I'm thinking along the lines of making a generic request handler (that follows the channels format) on every domain and have only one implementation of the channel for the basic request-response cycle. That way you would do something like that: (pseudo code)
```javascript
socket.connect()
let requestDriver = socket.channel("requests", {})
requestDriver.join().receive("ok", resp => { console.log("Connected to server", resp) })

requestHandler = {
  server_get: function(server_id) {
    msg = {args: {server_id: server_id}}
    return requestDriver.push("server.get", msg)
      .receive("ok", resp => { wrap_into_success_context(resp) })
      .receive("error", resp => { wrap_into_error_context(resp) })
  }
}
```

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/helix/151)

### CODE REVIEW

**Comment by mememori** [comment]
I'm implementing `3` for both public and authenticated sockets. It should operate on simple request topics.

Note that for things that could make use of a channel (with proper topic etc), we'll obviously use Channels.
Eg: a channel for a user logged into a server, that way it is notified everytime something changes on the server (new files, new log etc) or something like that

**Comment by mememori** [comment]
Last commit shows basically the idea:

```elixir
def handle_in(topic = "account." <> _, params, socket) do
  Account.handle_in(topic, params, socket)
end
```

Note that i am not particularly happy with the folder names for `router/*`. I think i'll rename it to `websocket` or `channels` as it doesnt have much to do with routing (the name is based on our legacy ws router)

**Comment by mememori** [comment]
Note that this PR is more or less a prototype, so some things might look ugly (like the folder "router" or the fact that we implemented two handler modules for request-response WS generic events on a single file on `account/ws/routes.ex`) but it is because this PR is more to prove that it works and that it will be nicer.

We'll eventually discuss again about this and define a better organization for those things. Anyway, i am actually liking a bit how it's becoming.

Things i might consider:
- Move the sockets to the root level just like `event.ex`
- Separate the contents of `account/ws/routes.ex` into two files

**Comment by mememori** [comment]
After talking with @renatomassaro, we've defined a few nice points that will not only make the WS api easier to use and maintain but also be more flexible:

1) Remove the "public" socket, so, that means that whenever a player has an active ws connection, it means that they are authenticated
2) Move the `account.login` and `account.create` public topics to a HTTP JSON API using Phoenix Routers and Phoenix Controllers
3) Replace Guardian's JWT with Phoenix Token to make it easier to maintain and to identify active sessions (that way we can invalidate specific sessions etc) and because, as we moved to a stateful approach, it becomes a bit redundant to have a stateless token (that had to be often checked against state)

**Comment by mememori** [comment]
TODO: review the return format for both the websocket and the http controllers

**Comment by renatomassaro** [comment]
I think at the lib/ folder we should add ws/ and http/ folders, and put there all files related to each driver. Feels better than having `socket.ex` and `http_router.ex` at the root level, so they could be `ws/socket.ex`, `ws/requests.ex`  and`http/router.ex`.

---

Reviewed 4 of 16 files at r1, 1 of 11 files at r2, 33 of 38 files at r4.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[config/config.exs, line 20 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJFipi0bY6JN0Z0WTg:-KhJFipi0bY6JN0Z0WTh:bly24n1) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/config/config.exs#L20)):*
> ```Elixir
>   pubsub: [
>     adapter: Phoenix.PubSub.PG2,
>     pool_size: 1,
> ```

What this pool size is in reference to? Couldn't find anything at phoenix docs (except the pool_size definition). We'll probably want to increase it in production but I need to know what it is xD

---

*[config/prod.exs, line 10 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJB--UKZ9PZTzGTqiW:-KhJB--VlFM7kqcRO-YK:b-hyh9yc) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/config/prod.exs#L10)):*
> ```Elixir
> config :helix, Helix.Endpoint,
>   server: true,
>   secret_key_base: "${HELIX_ENDPOINT_SECRET_KEY}",
> ```

We need to add a sanity check on run time to ensure the key is in fact set. If I'm not mistaken, if the above env var is not defined when starting the release, `secret_key_base` will be set to `${HELIX_ENDPOINT_SECRET_KEY}`, literally.

---

*[lib/endpoint.ex, line 4 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJBc5wq0V6ANt-ax8H:-KhJBc5xb_N1pF0tKeUT:bd5an4y) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/lib/endpoint.ex#L4)):*
> ```Elixir
>   use Phoenix.Endpoint, otp_app: :helix
> 
>   socket "/ws", Helix.Router.Socket.Player
> ```

Make path a config entry. I don't think we need to have it as an environment variable, in fact I'd say it's safer on prod environment for the path to be hard-coded on the config. That's because a release with the wrong envvar would make the server listen on a different port and totally not work (after all tests have passed). In prod we'll use "/".

EDIT: Okay, got it why it's /ws up here and / below. I'd rather switch the path  for each driver (api.hackerexperience.com/ for websockets, api.hackerexperience.com/v1/* for http). Is this setup possible? (without having to run two different instances of Phoenix)

---

*[lib/http_router.ex, line 13 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJEGk3hxpYyXM4cCjn:-KhJEGk3hxpYyXM4cCjo:b-bjvayb) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/lib/http_router.ex#L13)):*
> ```Elixir
>   end
> 
>   scope "/api/v1", as: :api_v1 do
> ```

No need for the /api since this will already be on the subdomain. The v1 is a good practice (some people prefer the version to be sent alongside the http header but luckily we are not these people)

---

*[lib/account/supervisor.ex, line 24 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJGQ3l6ROzrDwBMhQ4:-KhJGQ3mvs24cdPBTx8c:b-agg2jn) ([raw file](https://github.com/hackerexperience/helix/blob/0ac97e003ebc4b008b30ca4d6b6ca936305811a8/lib/account/supervisor.ex#L24)):*
> ```Elixir
>   end
> 
>   defp validate_guardian_config do
> ```

Add a function like this for Session validation.

Ensure the key is not null and with length greater than, say, 50. This way we have run-time safety that the key 1) is not null, 2) is not "${HELIX_ENDPOINT_SECRET_KEY}" and 3) is of reasonable size.

---

*[lib/account/service/api/account.ex, line 75 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJHNPxJU1dPkyhAnPl:-KhJHNPyKjOvhIhBI2UB:b108rlf) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/lib/account/service/api/account.ex#L75)):*
> ```Elixir
> 
>     if Account.check_password(account, password) do
>       {:ok, account}
> ```

On login you need to return the (session) token, so the client can authenticate on the websocket. Account.t has no token

EDIT: Oh, ok, I see what is going on. You are returning the token on the http /account/login call, but you are generating this token on the http driver. I think this is a business logic (login returns token) that should be encapsulated on the service api, since logins should always return the session, no matter which driver (or method, say, fb login) started the action.

---

*[lib/account/ws/routes.ex, line 13 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJIS1dZMvse4tLVALY:-KhJIS1dZMvse4tLVALZ:b-b75053) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/lib/account/ws/routes.ex#L13)):*
> ```Elixir
> 
>   def handle_in("account.logout", _params, socket) do
>     AccountController.logout(socket.assigns, %{})
> ```

Shouldn't the WS (or any driver) NOT call the controller directly?

---

*[lib/account/ws/channel/account.ex, line 15 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJIqA0o6JntP-Fnqpa:-KhJIqA0o6JntP-Fnqpb:b-wtwczx) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/lib/account/ws/channel/account.ex#L15)):*
> ```Elixir
>       {:ok, socket}
>     else
>       {:error, %{reason: "can't join another user's notification channel"}}
> ```

If this reason is the one who will be sent to the client, I see absolutely no reason to not start with an upper case letters. Erlang errors/exceptions are lower case, ok, but the client does not care about the implementation. Whatever, this makes no difference, it's an insignificant improvement on developer UX.

---

*[priv/repo/account/migrations/20170409040234_add_player_session.exs, line 1 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJJz1RhvrEN39uwHJt:-KhJJz1RhvrEN39uwHJu:b-k3xg40) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/priv/repo/account/migrations/20170409040234_add_player_session.exs#L1)):*
> ```Elixir
> defmodule Helix.Account.Repo.Migrations.AddPlayerSession do
> ```

Are you moving this to Entity? We've discussed this yesterday and it's still marked as wip, so probably you are already doing this, just a reminder xD

---

*[test/socket_test.exs, line 18 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJK8D_lZPBx_jONK72:-KhJK8D_lZPBx_jONK73:bb6f6cf) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/test/socket_test.exs#L18)):*
> ```Elixir
>   end
> 
>   test "socket is connectable only with valid JWT token" do
> ```

-JWT

---

*[test/socket_test.exs, line 40 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJKDrgW5GJAoGhEbmx:-KhJKDrgW5GJAoGhEbmy:bmg1p74) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/test/socket_test.exs#L40)):*
> ```Elixir
>     id2 = Socket.id(socket2)
> 
>     # Both socket0 and socket1 use a JWT that gives access to the same account
> ```

s/JWT/token

---

*[test/account/service/api/account_test.exs, line 68 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJLfKDU0HgzJXkOkW3:-KhJLfKDU0HgzJXkOkW4:b-nle1ga) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/test/account/service/api/account_test.exs#L68)):*
> ```Elixir
>     end
> 
>     test "cannot use email as login credential" do
> ```

this will likely change in the future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/151#-:-KhJEvIjmPUppfNTmcfR:b-7h28u3)*

**Comment by mememori** [comment]
I agree with you, but since it was definitely just one router and just one socket, i preferred at the moment to keep it as a single file in the root and dedicate the folders to domains (as i doubt we'll have many more generic things related to implementation for http or ws) but i'll change it

---

Reviewed 2 of 16 files at r1, 13 of 38 files at r4.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[config/config.exs, line 20 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJFipi0bY6JN0Z0WTg:-KhJOKAKPD964Gmb02cd:bcfvjc7) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/config/config.exs#L20)):*
Yup, i know it, i left as 1 because it is not relevant until we are almost stable.

Pool size configuration definition is here: https://hexdocs.pm/phoenix_pubsub/Phoenix.PubSub.PG2.html

>  Both the size of the local pubsub server pool and subscriber shard size. Defaults the number of schedulers (cores). A single pool is often enough for most use-cases, but for high subscriber counts on a single topic or greater than 1M clients, a pool size equal to the number of schedulers (cores) is a well rounded size.

Basically, if we have too few subscribers (ie: players), it's better to have pool_size 1 as one single instance can take care of anything. If we get big enough, it's a good idea to (automatically) shard it to the amount of schedulers we have so it can be 100% paralelized (ie: in the ideal case, when the subscribers of a topic are requested, all cores work fetching it at the same time)

---

*[config/prod.exs, line 10 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJB--UKZ9PZTzGTqiW:-KhJOziAmuoiAeWAIyBx:byw9rr0) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/config/prod.exs#L10)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

We need to add a sanity check on run time to ensure the key is in fact set. If I'm not mistaken, if the above env var is not defined when starting the release, `secret_key_base` will be set to `${HELIX_ENDPOINT_SECRET_KEY}`, literally.
</blockquote></details>

Before you wrote your PR, i was already doing that and it's done :)

---

*[lib/application.ex, line 9 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJGpobK8O92MuQcar4:-KhJGpobK8O92MuQcar5:b-m68qfh) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/lib/application.ex#L9)):*
> ```Elixir
>   def start(_type, _args) do
>     children = [
>       # worker(HELF.Broker, []),
> ```

This is temporarily commented because i think we might reenable it in the future

---

*[lib/endpoint.ex, line 4 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJBc5wq0V6ANt-ax8H:-KhJP33wLtgIp0MqAi65:b-yjlc9e) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/lib/endpoint.ex#L4)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

Make path a config entry. I don't think we need to have it as an environment variable, in fact I'd say it's safer on prod environment for the path to be hard-coded on the config. That's because a release with the wrong envvar would make the server listen on a different port and totally not work (after all tests have passed). In prod we'll use "/".

EDIT: Okay, got it why it's /ws up here and / below. I'd rather switch the path  for each driver (api.hackerexperience.com/ for websockets, api.hackerexperience.com/v1/* for http). Is this setup possible? (without having to run two different instances of Phoenix)
</blockquote></details>

I'm most certain we can. I'm still not 100% sure why both are on the `api` subdomain. But this is doable by

1) Ensuring that our endpoint instance runs on the `api` subdomain
2) Setting the socket to `/`
3) Setting the api scope to `/v1`
4) Ensuring that a proxy will provide `hackerexperience.com` (or whatever it should be) with the client

---

*[lib/http_router.ex, line 13 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJEGk3hxpYyXM4cCjn:-KhJPdS3mAzKKNkAd0uP:bb6mt9b) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/lib/http_router.ex#L13)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

No need for the /api since this will already be on the subdomain. The v1 is a good practice (some people prefer the version to be sent alongside the http header but luckily we are not these people)
</blockquote></details>

:+1:

---

*[lib/socket.ex, line 20 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJIocfUBKNTSCoHXJY:-KhJIocgkJZJo4AZFEfb:b-9yvuy4) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/lib/socket.ex#L20)):*
> ```Elixir
>           |> assign(:session, session)
> 
>         {:ok, socket}
> ```

Personally i feel so happy with this i can't explain.

This tiny excerpt of code means that when an user has access to the game mechanics topics we don't have to do any additional validation because we already authenticated them.

And by scoping those actions inside the socket, it means that there is no way to access them besides using the socket (which requires authentication), so, the overall code got way simpler now :relaxed:

---

*[lib/socket.ex, line 41 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJJJBN7h4pcuqDPqTt:-KhJJJBN7h4pcuqDPqTu:b-8el5ie) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/lib/socket.ex#L41)):*
> ```Elixir
> 
>   def join(_topic, _message, socket) do
>     # God in the command
> ```

:top:

---

*[lib/socket.ex, line 47 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJJLCk2dHD5sb00l4O:-KhJJLCk2dHD5sb00l4P:b-nx79tm) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/lib/socket.ex#L47)):*
> ```Elixir
>   def handle_in(topic = "account." <> _, params, socket) do
>     Account.handle_in(topic, params, socket)
>   end
> ```

I'm considering making explicit the possible topics instead of delegating it to the context module.

Eg:

```elixir
def handle_in("account.logout", params, socket),
  do: Account.logout(params, socket)
def handle_in("account.idk", params, socket),
  do: Account.idk(params, socket)
```

So it's clearer, more obvious and less prone to bugs.

Also, we already are doing that for HTTP requests because the router must route to a controller action, so, i don't see an special burden on doing that here too

---

*[lib/account/supervisor.ex, line 24 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJGQ3l6ROzrDwBMhQ4:-KhJPqrVgIHIsqYooJnG:b-ig00la) ([raw file](https://github.com/hackerexperience/helix/blob/0ac97e003ebc4b008b30ca4d6b6ca936305811a8/lib/account/supervisor.ex#L24)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

Add a function like this for Session validation.

Ensure the key is not null and with length greater than, say, 50. This way we have run-time safety that the key 1) is not null, 2) is not "${HELIX_ENDPOINT_SECRET_KEY}" and 3) is of reasonable size.
</blockquote></details>

I repeat the comment i did on the config: this is already done on my local worktree \o/ :grin:

---

*[lib/account/service/api/account.ex, line 75 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJHNPxJU1dPkyhAnPl:-KhJPxJjUIfW6Krftb0e:b-e3ts82) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/lib/account/service/api/account.ex#L75)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

On login you need to return the (session) token, so the client can authenticate on the websocket. Account.t has no token

EDIT: Oh, ok, I see what is going on. You are returning the token on the http /account/login call, but you are generating this token on the http driver. I think this is a business logic (login returns token) that should be encapsulated on the service api, since logins should always return the session, no matter which driver (or method, say, fb login) started the action.
</blockquote></details>

I agree with you. Updating it

---

*[lib/account/ws/routes.ex, line 13 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJIS1dZMvse4tLVALY:-KhJN6dUCkRXMHm1tLMG:b-b2rhhb) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/lib/account/ws/routes.ex#L13)):*
> alias Helix.Account.WS.Controller.Account, as: AccountController
:)

---

*[lib/account/ws/channel/account.ex, line 15 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJIqA0o6JntP-Fnqpa:-KhJQnaZLbgKDbYVwakG:b4o8bll) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/lib/account/ws/channel/account.ex#L15)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

If this reason is the one who will be sent to the client, I see absolutely no reason to not start with an upper case letters. Erlang errors/exceptions are lower case, ok, but the client does not care about the implementation. Whatever, this makes no difference, it's an insignificant improvement on developer UX.
</blockquote></details>

Actually this is a short example that i did mostly to test if it is working. I plan to do a new PR in the future just to implement view protocols and to standardize the returns whenever possible, so, i'll push this to upstream anyway

---

*[priv/repo/account/migrations/20170409040234_add_player_session.exs, line 1 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJJz1RhvrEN39uwHJt:-KhJR6u_zxDOIUn8VS-P:b-8ejam1) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/priv/repo/account/migrations/20170409040234_add_player_session.exs#L1)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

Are you moving this to Entity? We've discussed this yesterday and it's still marked as wip, so probably you are already doing this, just a reminder xD
</blockquote></details>

That's true, but as i just discussed with you, i'll let this become rework in the future because it would add me a lot of work to provide this versatility right now and we don't even know if this will ever be used/needed

---

*[test/socket_test.exs, line 18 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJK8D_lZPBx_jONK72:-KhJRXMVRakPF_OpfUgD:b-y59xdg) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/test/socket_test.exs#L18)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

-JWT
</blockquote></details>

Thanks :+1:

---

*[test/socket_test.exs, line 40 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJKDrgW5GJAoGhEbmx:-KhJRZucfL9vjr6fp6-S:b-4mh7hp) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/test/socket_test.exs#L40)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

s/JWT/token
</blockquote></details>

Domo arigato mr roboto :robot:

Also, i'll temporarily delete this test because it was relevant before, now a connection id points to a session, so this only passed because both connections used the same session token

---

*[test/account/service/api/account_test.exs, line 68 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJLfKDU0HgzJXkOkW3:-KhJRu7_9rqYwJMKuptE:bb7pcsz) ([raw file](https://github.com/hackerexperience/helix/blob/42f2750a4fbcec1f2c752a9f7cb92318930b28cb/test/account/service/api/account_test.exs#L68)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

this will likely change in the future.
</blockquote></details>

true

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/151#-:-KhJO4NZl9m7hwDz__R8:b-8uu2qb)*

**Comment by mememori** [comment]
:lgtm_strong: 

---

Reviewed 1 of 46 files at r4, 5 of 10 files at r5, 24 of 24 files at r6.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[config/prod.exs, line 10 at r6](https://reviewable.io:443/reviews/hackerexperience/helix/151#-KhJUZiOV6-s00Fx8vxs:-KhJUZiOV6-s00Fx8vxt:b-iwez4a) ([raw file](https://github.com/hackerexperience/helix/blob/2c0d65e1c6efe2281e89f2da15660ed4fdc8f430/config/prod.exs#L10)):*
> ```Elixir
> config :helix, Helix.Endpoint,
>   server: true,
>   url: [host: "${HELIX_ENDPOINT_URL}", port: 80],
> ```

@renatomassaro whenever possible, test this for me, pl0x

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/151#-:-KhJVpLKejmvZ4BsjxHZ:b-uwkowd)*

**Comment by renatomassaro** [comment]
:lgtm:

---

Reviewed 2 of 25 files at r6, 4 of 4 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/151#-:-KhJg1nAj6C0TqxXHVVC:bnfp4nl)*

**Pull request merged**
