### PR TITLE
Dialyzer

### LINKED ISSUE #25: Fix dialyzer errors

### PR DESCRIPTION
**Pull request by mememori**
Fix most dialyzer erros. Closes #25 

Note this is going to become a humongous PR because it will

- Fix type errors
- ~Apply new style guides~ Deferred to #33
- Fix issues on code
- Fix breaking code that causes false-positives (eg: Account.login) and test it
- Improve JWT handling (taking over Phabricator's D63)
- ~Improve code to provide better type handling (eg: ComponentSpec)~ Deferred to #32
- Fix some credo errors that are somewhat false-positives

I'm taking over this PR from @kress95 's work

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/helix/26)

### CODE REVIEW

**Comment by mememori** [comment]
Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[apps/account/lib/account/controller/account_service.ex, line 61 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/26#-KfkmsyhJ2Jtiq3g3Pn_:-KfkmsyhJ2Jtiq3g3Pna:bh3efmg) ([raw file](https://github.com/hackerexperience/helix/blob/21d5a6aa0ed501117718b71472dde60473e3f357/apps/account/lib/account/controller/account_service.ex#L61)):*
> ```Elixir
>   def handle_call({:account, :login, email, password}, _from, state) do
>     with \
>       {:ok, account_id} <- AccountController.login(email, password),
> ```

This is actually wrong, `AccountController.login` expects username and password, not email and password

---

*[apps/hardware/lib/hardware/model/component_spec.ex, line 18 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/26#-KfknU8lmTqVguf67g4O:-KfknU8mBvH5o3n8txQZ:b-intny3) ([raw file](https://github.com/hackerexperience/helix/blob/21d5a6aa0ed501117718b71472dde60473e3f357/apps/hardware/lib/hardware/model/component_spec.ex#L18)):*
> ```Elixir
>     component_type: String.t,
>     spec: %{}}
>   @type update_params :: %{spec: %{}}
> ```

I'll add some spice to it : typespec the possible `spec`s and use them as accepted types here

---

*[apps/hardware/lib/hardware/model/component/cpu.ex, line 51 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/26#-KfkncVwRfpQza8Hw79c:-KfkncVwRfpQza8Hw79d:beggx7e) ([raw file](https://github.com/hackerexperience/helix/blob/21d5a6aa0ed501117718b71472dde60473e3f357/apps/hardware/lib/hardware/model/component/cpu.ex#L51)):*
> ```Elixir
>     do: changeset(struct, params)
> 
>   @spec changeset(t | Ecto.Changeset.t, %{any => any}) :: Ecto.Changeset.t
> ```

This is not really correct.

`Ecto.Schema.t` is anything that uses `Ecto.Schema`'s `use (...) schema`, so, any model. The success typing here is `t`; `t` implements `Ecto.Schema`

---

*[apps/hardware/lib/hardware/model/component/hdd.ex, line 48 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/26#-Kfko-_Gcn5YNN3nTmxp:-Kfko-_Gcn5YNN3nTmxq:beggx7e) ([raw file](https://github.com/hackerexperience/helix/blob/ae31212d9ab91f3c3fe40e668431fe3ce7414eda/apps/hardware/lib/hardware/model/component/hdd.ex#L48)):*
> ```Elixir
>     do: changeset(struct, params)
> 
>   @spec changeset(t | Ecto.Schema.t | Ecto.Changeset.t, %{any => any}) ::
> ```

This is not really correct.

`Ecto.Schema.t` is anything that uses `Ecto.Schema`'s `use (...) schema`, so, any model. The success typing here is `t`; `t` implements `Ecto.Schema`

---

*[apps/hardware/lib/hardware/model/component/nic.ex, line 59 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/26#-Kfko19-BYm-FEKJl65W:-Kfko19-BYm-FEKJl65X:beggx7e) ([raw file](https://github.com/hackerexperience/helix/blob/ae31212d9ab91f3c3fe40e668431fe3ce7414eda/apps/hardware/lib/hardware/model/component/nic.ex#L59)):*
> ```Elixir
>     do: changeset(struct, params)
> 
>   @spec changeset(t | Ecto.Schema.t | Ecto.Changeset.t, %{any => any}) ::
> ```

This is not really correct.

`Ecto.Schema.t` is anything that uses `Ecto.Schema`'s `use (...) schema`, so, any model. The success typing here is `t`; `t` implements `Ecto.Schema`

---

*[apps/hardware/lib/hardware/model/component/ram.ex, line 48 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/26#-Kfko317EY2s_fr-0CVM:-Kfko317EY2s_fr-0CVN:beggx7e) ([raw file](https://github.com/hackerexperience/helix/blob/ae31212d9ab91f3c3fe40e668431fe3ce7414eda/apps/hardware/lib/hardware/model/component/ram.ex#L48)):*
> ```Elixir
>     do: changeset(struct, params)
> 
>   @spec changeset(t | Ecto.Schema.t | Ecto.Changeset.t, %{any => any}) ::
> ```

This is not really correct.

`Ecto.Schema.t` is anything that uses `Ecto.Schema`'s `use (...) schema`, so, any model. The success typing here is `t`; `t` implements `Ecto.Schema`

---

*[apps/server/lib/server/controller/server_service.ex, line 53 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/26#-KfkoKjkldDB5Ge05jUZ:-KfkoKjkldDB5Ge05jU_:bv7zqrt) ([raw file](https://github.com/hackerexperience/helix/blob/ae31212d9ab91f3c3fe40e668431fe3ce7414eda/apps/server/lib/server/controller/server_service.ex#L53)):*
> ```Elixir
>     }
> 
>     GenServer.call(pid, {:server, :create, params})
> ```

You didn't update here to the new `call` format you defined, so this is breaking all tests

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/26)*

**Comment by mememori** [comment]
> Adding 220 modules to dialyxir_erlang-19.2_elixir-1.4.2.plt
> Killed
> script returned exit code 137

Nao fode, Joaquim :unamused:

**Comment by renatomassaro** [comment]
Reviewed 12 of 38 files at r2, 16 of 20 files at r3, 19 of 19 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/26)*

**Comment by renatomassaro** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[apps/helix_account/lib/ws/routing/routes.ex, line 1 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/26#-KfrztPCRgduHHeYsKhU:-KfrztPCRgduHHeYsKhV:b-qvsumu) ([raw file](https://github.com/hackerexperience/helix/blob/9b4a07b32253fdeb4d3548d5eb71ce55506a329e/apps/helix_account/lib/ws/routing/routes.ex#L1)):*
> ```Elixir
> defmodule Helix.Account.WS.Routes do
> ```

As we've discussed, let's move this file `routes.ex` into the root folder `ws`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/26)*

**Comment by mememori** [comment]
Reviewed 20 of 38 files at r2, 20 of 21 files at r3, 16 of 19 files at r4.
Review status: 46 of 47 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[apps/helix_account/lib/ws/routes.ex, line 1 at r4](https://reviewable.io:443/reviews/hackerexperience/helix/26#-KfrztPCRgduHHeYsKhU:-Kfs0q67D4discyzmhY9:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/9b4a07b32253fdeb4d3548d5eb71ce55506a329e/apps/helix_account/lib/ws/routes.ex#L1)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

As we've discussed, let's move this file `routes.ex` into the root folder `ws`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/26)*

**Comment by renatomassaro** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/26#-:-Kfs5aT-lN2Cj6QO4_k8:bnfp4nl)*

**Comment by mememori** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/26)*

**Pull request merged**
