### PR TITLE
Rename file type

### PR DESCRIPTION
**Pull request by kress95**
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/helix/32)

### CODE REVIEW

**Comment by mememori** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[apps/helix_software/lib/software/model/module_role.ex, line 38 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/32#-KfqZ-YtQzH5DiXbW94z:-KfqZ-YtQzH5DiXbW95-:b-133nk8) ([raw file](https://github.com/hackerexperience/helix/blob/2300d603d54e1178e14e12fd908feb536ecfca66/apps/helix_software/lib/software/model/module_role.ex#L38)):*
> ```Elixir
>     |> cast(params, @creation_fields)
>     |> validate_required([:module_role, :software_type])
>     |> unique_constraint(:module_role, name: :software_type_module_role_unique_constraint)
> ```

Why do you always ignore the things i tell you to do (or not to) ?

---

*[apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs, line 17 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/32#-KfqZnQCFNoAvnu01Xhf:-KfqZnQCFNoAvnu01Xhg:b-9q9jk7) ([raw file](https://github.com/hackerexperience/helix/blob/2300d603d54e1178e14e12fd908feb536ecfca66/apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs#L17)):*
> ```Elixir
>     create table(:software_types, primary_key: false) do
>       add :software_type, :string, primary_key: true
>       add :extension, :string
> ```

not null

---

*[apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs, line 22 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/32#-KfqZiG_TY0ELHVRc-BQ:-KfqZiG_TY0ELHVRc-BR:bjt6z8x) ([raw file](https://github.com/hackerexperience/helix/blob/2300d603d54e1178e14e12fd908feb536ecfca66/apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs#L22)):*
> ```Elixir
>     alter table(:files) do
>       add :software_type,
>         references(:software_types, column: :software_type, type: :string)
> ```

same line, not null

---

*[apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs, line 27 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/32#-KfqZgn6ptjMQdtoR8HJ:-KfqZgn6ptjMQdtoR8HK:bjt6z8x) ([raw file](https://github.com/hackerexperience/helix/blob/2300d603d54e1178e14e12fd908feb536ecfca66/apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs#L27)):*
> ```Elixir
>     alter table(:module_roles) do
>       add :software_type,
>         references(:software_types, column: :software_type, type: :string)
> ```

same line, not null

---

*[apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs, line 30 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/32#-KfqZfDTvnzcxuhkKC_q:-KfqZfDTvnzcxuhkKC_r:b-133nk8) ([raw file](https://github.com/hackerexperience/helix/blob/2300d603d54e1178e14e12fd908feb536ecfca66/apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs#L30)):*
> ```Elixir
>     end
> 
>     create unique_index(:files, [:storage_id, :file_path, :name, :software_type], name: :unique_file_path_index)
> ```

Why do you always ignore the things i tell you to do (or not to) ?

---

*[apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs, line 32 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/32#-KfqZW2sjdy0jCunxakT:-KfqZW2sjdy0jCunxakU:b-7owrbg) ([raw file](https://github.com/hackerexperience/helix/blob/2300d603d54e1178e14e12fd908feb536ecfca66/apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs#L32)):*
> ```Elixir
>     create unique_index(:files, [:storage_id, :file_path, :name, :software_type], name: :unique_file_path_index)
>   end
> end
> ```

Why did you kept the `file_types` table instead of removing it ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/32)*

**Comment by kress95** [comment]
*[apps/helix_software/lib/software/model/module_role.ex, line 38 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/32#-KfqZ-YtQzH5DiXbW94z:-KfqvdVmrLLW1LXuLWAY:b-turaub) ([raw file](https://github.com/hackerexperience/helix/blob/2300d603d54e1178e14e12fd908feb536ecfca66/apps/helix_software/lib/software/model/module_role.ex#L38)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

Why do you always ignore the things i tell you to do (or not to) ?
</blockquote></details>

What's wrong?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/32)*

**Comment by mememori** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[apps/helix_software/lib/software/model/module_role.ex, line 38 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/32#-KfqZ-YtQzH5DiXbW94z:-KfqwobdL55dEjAfLIbe:byl1vi7) ([raw file](https://github.com/hackerexperience/helix/blob/2300d603d54e1178e14e12fd908feb536ecfca66/apps/helix_software/lib/software/model/module_role.ex#L38)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

What's wrong?
</blockquote></details>

Two problems:

1)


For someone that is not you, what can that person assume that `unique_file_path_index` and `software_type_module_role_unique_constraint` are ?

2)
As you might 've noticed from the image above, that very index does not exists

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/32)*

**Comment by kress95** [comment]
Review status: 6 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs, line 17 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/32#-KfqZnQCFNoAvnu01Xhf:-Kfr-DdVmzx4yQzkr892:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/2300d603d54e1178e14e12fd908feb536ecfca66/apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs#L17)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

not null
</blockquote></details>

Done.

---

*[apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs, line 22 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/32#-KfqZiG_TY0ELHVRc-BQ:-Kfr-GytiRirz9daEnA8:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/2300d603d54e1178e14e12fd908feb536ecfca66/apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs#L22)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

same line, not null
</blockquote></details>

Done.

---

*[apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs, line 27 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/32#-KfqZgn6ptjMQdtoR8HJ:-Kfr-JAFXnECxtN5jdmz:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/2300d603d54e1178e14e12fd908feb536ecfca66/apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs#L27)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

same line, not null
</blockquote></details>

Done.

---

*[apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs, line 30 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/32#-KfqZfDTvnzcxuhkKC_q:-Kfr-_tAwVEmDGKsIZhH:b-tkewy1) ([raw file](https://github.com/hackerexperience/helix/blob/2300d603d54e1178e14e12fd908feb536ecfca66/apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs#L30)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

Why do you always ignore the things i tell you to do (or not to) ?
</blockquote></details>

It's good now as `unique_file_location_index`?

---

*[apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs, line 32 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/32#-KfqZW2sjdy0jCunxakT:-Kfr-KakWTg1ALBkz7Pp:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/2300d603d54e1178e14e12fd908feb536ecfca66/apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs#L32)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

Why did you kept the `file_types` table instead of removing it ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/32)*

**Comment by kress95** [comment]
Review status: 6 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[apps/helix_software/lib/software/model/module_role.ex, line 38 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/32#-KfqZ-YtQzH5DiXbW94z:-KfrEOLPsuWjJS587SlS:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/2300d603d54e1178e14e12fd908feb536ecfca66/apps/helix_software/lib/software/model/module_role.ex#L38)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

Two problems:

1)


For someone that is not you, what can that person assume that `unique_file_path_index` and `software_type_module_role_unique_constraint` are ?

2)
As you might 've noticed from the image above, that very index does not exists
</blockquote></details>

Done.

---

*[apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs, line 17 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/32#-KfqZnQCFNoAvnu01Xhf:-KfrEMMG52jLfjlOm_s6:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/2300d603d54e1178e14e12fd908feb536ecfca66/apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs#L17)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs, line 22 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/32#-KfqZiG_TY0ELHVRc-BQ:-KfrEMmc9oIBIbUeJHD4:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/2300d603d54e1178e14e12fd908feb536ecfca66/apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs#L22)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs, line 27 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/32#-KfqZgn6ptjMQdtoR8HJ:-KfrERuoc7LZIuT9bema:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/2300d603d54e1178e14e12fd908feb536ecfca66/apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs#L27)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs, line 30 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/32#-KfqZfDTvnzcxuhkKC_q:-KfrESV20ShtQKWulCKp:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/2300d603d54e1178e14e12fd908feb536ecfca66/apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs#L30)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

It's good now as `unique_file_location_index`?
</blockquote></details>

Done.

---

*[apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs, line 32 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/32#-KfqZW2sjdy0jCunxakT:-KfrEd3fYF3hVENi9jpE:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/2300d603d54e1178e14e12fd908feb536ecfca66/apps/helix_software/priv/repo/migrations/20170321200902_rename-file-type-to-software-type.exs#L32)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/32)*

**Comment by kress95** [comment]
I believe this is ready for revision, any reason to remove it from there, @mememori ?

**Comment by mememori** [comment]
>I believe this is ready for revision, any reason to remove it from there, @mememori ? (but the conflicting file)

The fact that you are ignoring what i said to you. I explained the problem [on this PR](https://github.com/HackerExperience/Helix/pull/32#issuecomment-288467981), [on another PR](https://github.com/HackerExperience/Helix/pull/18#issuecomment-287920769) and personally about inadequate or generic index names.

If you don't remember what i explained to you personally about the problem of generic index names, read this [stackoverflow question](http://stackoverflow.com/questions/27306539/at-what-level-do-postgres-index-names-need-to-be-unique)

I can't review this PR until you fix that issue

And then,
> Please, ensure that the PR you want reviewed is complete before you move it [...] to the "Review" pipeline.
>
> To do so, execute the appropriate tests to ensure that the purpose of the PR is achieved (this might include debugging directly on the database or on the interactive terminal) [, check it with `credo` and `dialyzer`] and review it yourself; if it seems ok after that, then move it to my review pipeline [and i'll be glad to review it]

**Comment by kress95** [comment]
I renamed both indexes to:

```
unique_software_type_for_module_role_index
unique_file_location_index
```

I believe that the later is OK, I don't know about the former, but I can't think of a better name for it.

**Comment by kress95** [comment]
This last push is not changing anything, it's just a rebase.
I'm not requesting a revision now, just waiting for your input on my last question.

I'll work on something else for now.

**Comment by kress95** [comment]
Welp, looks like git isn't notifying my [amends](https://github.com/kress95/Helix/commit/8da3dddbf267f5649ce96203e5a2670a05055cc6).

The current branch is rebased with master and (locally) passing on link, type analysis and tests.
The index naming is also dropped, I'm using an Ecto generated name instead.

**Comment by mememori** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[apps/helix_software/lib/software/model/file.ex, line 84 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/32#-KgFUX08tEEK3PuGp9OL:-KgFUX08tEEK3PuGp9OM:b-gzpk5x) ([raw file](https://github.com/hackerexperience/helix/blob/ed81b7a3e5b3de1ed116ef238e406670de8b422a/apps/helix_software/lib/software/model/file.ex#L84)):*
> ```Elixir
>       [:name, :file_path, :file_size, :software_type, :storage_id])
>     |> validate_number(:file_size, greater_than: 0)
>     |> unique_constraint(:file_path, name: :files_storage_id_file_path_name_software_type_index)
> ```

```elixir
��� [R] ��� Line is too long (max is 80, was 96).
���       apps/helix_software/lib/software/model/file.ex:84:81 (Helix.Software.Model.File.generic_validations)
```

---

*[apps/helix_software/lib/software/model/module_role.ex, line 38 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/32#-KgFUQd5J-ru7aTBCXcD:-KgFUQd5J-ru7aTBCXcE:b-ni7v5d) ([raw file](https://github.com/hackerexperience/helix/blob/ed81b7a3e5b3de1ed116ef238e406670de8b422a/apps/helix_software/lib/software/model/module_role.ex#L38)):*
> ```Elixir
>     |> cast(params, @creation_fields)
>     |> validate_required([:module_role, :software_type])
>     |> unique_constraint(:module_role, name: :module_roles_module_role_software_type_index)
> ```

```elixir
��� [R] ��� Line is too long (max is 80, was 91).
���       apps/helix_software/lib/software/model/module_role.ex:38:81 (Helix.Software.Model.ModuleRole.create_changeset)
```

---

*[apps/helix_software/test/controller/file_module_test.exs, line 26 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/32#-KgFU_85Mgl5oXedRGpA:-KgFU_85Mgl5oXedRGpB:bpfk9w2) ([raw file](https://github.com/hackerexperience/helix/blob/ed81b7a3e5b3de1ed116ef238e406670de8b422a/apps/helix_software/test/controller/file_module_test.exs#L26)):*
> ```Elixir
>     module_roles = generate_module_roles(f.software_type)
> 
>     assert {:ok, file_modules} = FileModuleController.create(f, module_roles)
> ```

```elixir
assert {:ok, ^module_roles} ...
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/32)*

**Comment by mememori** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/32#-:-KgGQFBetxeoC1ZXXSgt:bnfp4nl)*

**Pull request merged**
