### PR TITLE
View improvement

### PR DESCRIPTION
**Pull request by mememori**
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/helix/207)

### CODE REVIEW

**Comment by mememori** [comment]
I hate to ship a PR that does totally different things (like improving our CI steps and also improving our websocket views) but sometimes i am too lazy to make two PRs 💁

**Comment by renatomassaro** [comment]
You shouldn't. It would give you yet another github contribution :nerd_face:

**Comment by renatomassaro** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 12 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/207#-KjoIkeTvwcZpfdSZZxI:-KjoIkeTvwcZpfdSZZxJ:b-7d384y) ([raw file](https://github.com/hackerexperience/helix/blob/3e172a37ec04d4cb092ef0f5e137ed0aedc10c22/.travis.yml#L12)):*
> ```YAML
> after_script:
>   - mix deps.get
>   - mix inch.report
> ```

As stated, this compiles again. If possible append it to the script line or use `MIX_ENV=test mix inch.report`. Note that in this case I'm not 100% sure the build is cached, since `after script` may run on a different container.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/207)*

**Comment by mememori** [comment]
Well, since you already reviewed, i'll merge this PR as is now and create a new PR solely for real work on views

**Comment by renatomassaro** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/207)*

**Comment by mememori** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[.travis.yml, line 12 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/207#-KjoIkeTvwcZpfdSZZxI:-KjoPrKq-uH8_-dsIxJF:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/3e172a37ec04d4cb092ef0f5e137ed0aedc10c22/.travis.yml#L12)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

As stated, this compiles again. If possible append it to the script line or use `MIX_ENV=test mix inch.report`. Note that in this case I'm not 100% sure the build is cached, since `after script` may run on a different container.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/207)*

**Pull request merged**
