### PR TITLE
Cracker flow

### PR DESCRIPTION
**Pull request by mememori**
- [x] Move cracker flow to file execute flow
- [ ] Test flow
- [x] Improve cracker model
- [x] Test cracker model
- [ ] Test cracker reaction to events

This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/helix/249)

### CODE REVIEW

**Comment by renatomassaro** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[lib/process/event/cracker.ex, line 48 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/249#-KrYMaLuCa8aCJfgW1-Q:-KrYMaLvTyK6D6-F-164:b-sccsy9) ([raw file](https://github.com/hackerexperience/helix/blob/948a58afd5b3b11f39ee8a4aec57a9b935b00156/lib/process/event/cracker.ex#L48)):*
> ```Elixir
>   @spec update_on_database([Changeset.t]) ::
>     {:ok, MapSet.t(Server.id)}
>   defp update_on_database(changesets) do
> ```

docp explaining why this exists / what it does

---

*[lib/process/event/cracker.ex, line 62 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/249#-KrYMrw9IL3cnm4GFO3R:-KrYMrwAFr40-YWX1inz:b-lgkbnw) ([raw file](https://github.com/hackerexperience/helix/blob/948a58afd5b3b11f39ee8a4aec57a9b935b00156/lib/process/event/cracker.ex#L62)):*
> ```Elixir
>   @spec notify_top({:ok, MapSet.t(Server.id)}) ::
>     :ok
>   defp notify_top({:ok, gateways}),
> ```

docp why is it notifying top

---

*[lib/software/model/software_type/cracker/events.ex, line 13 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/249#-KrYNThs2ymruW9ljKbX:-KrYNThs2ymruW9ljKbY:b-pcnfy9) ([raw file](https://github.com/hackerexperience/helix/blob/948a58afd5b3b11f39ee8a4aec57a9b935b00156/lib/software/model/software_type/cracker/events.ex#L13)):*
> ```Elixir
>     server_id: Server.id,
>     server_ip: IPv4.t,
>     server_type: term
> ```

Server.type?

---

*[test/software/model/software_type/cracker/process_type_test.exs, line 24 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/249#-KrYO5aG8y1tuhumPh4P:-KrYO5aG8y1tuhumPh4Q:bp9fh64) ([raw file](https://github.com/hackerexperience/helix/blob/948a58afd5b3b11f39ee8a4aec57a9b935b00156/test/software/model/software_type/cracker/process_type_test.exs#L24)):*
> ```Elixir
>       |> Enum.map(&({&1.software_module, &1.module_version}))
>       |> :maps.from_list()
>     end))
> ```

If/when you need this function again before working on file_modules, move it to SoftwareFactory, with `:cracker` or `:$file_type` being passed as argument.

---

*[test/software/model/software_type/log_forge/process_type_test.exs, line 23 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/249#-KrYVfCniobCpJRfeJ6F:-KrYVfCoVjjvpfA48yp_:b-x2me4m) ([raw file](https://github.com/hackerexperience/helix/blob/948a58afd5b3b11f39ee8a4aec57a9b935b00156/test/software/model/software_type/log_forge/process_type_test.exs#L23)):*
> ```Elixir
>       |> Enum.map(&({&1.software_module, &1.module_version}))
>       |> :maps.from_list()
>     end))
> ```

Oh, you do use somewhere. Move it to SoftwareFactory, with the file type as param. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/249)*

**Comment by mememori** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[lib/process/event/cracker.ex, line 48 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/249#-KrYMaLuCa8aCJfgW1-Q:-KrYX1d1aPECQkY4GpcS:bb6un1j) ([raw file](https://github.com/hackerexperience/helix/blob/948a58afd5b3b11f39ee8a4aec57a9b935b00156/lib/process/event/cracker.ex#L48)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

docp explaining why this exists / what it does
</blockquote></details>

Done

---

*[lib/process/event/cracker.ex, line 62 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/249#-KrYMrw9IL3cnm4GFO3R:-KrYX2q3MxR4IvEwyTC8:bb6un1j) ([raw file](https://github.com/hackerexperience/helix/blob/948a58afd5b3b11f39ee8a4aec57a9b935b00156/lib/process/event/cracker.ex#L62)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

docp why is it notifying top
</blockquote></details>

Done

---

*[lib/software/model/software_type/cracker/events.ex, line 13 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/249#-KrYNThs2ymruW9ljKbX:-KrYX3lcoqBYYEsyOeOC:b-pqihkz) ([raw file](https://github.com/hackerexperience/helix/blob/948a58afd5b3b11f39ee8a4aec57a9b935b00156/lib/software/model/software_type/cracker/events.ex#L13)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

Server.type?
</blockquote></details>

This doesn't exist and will be set as soon as we implement the Server.type as atoms because yes

---

*[test/software/model/software_type/cracker/process_type_test.exs, line 24 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/249#-KrYO5aG8y1tuhumPh4P:-KrYXCx2TbKLzFi-1l27:b-olsbp4) ([raw file](https://github.com/hackerexperience/helix/blob/948a58afd5b3b11f39ee8a4aec57a9b935b00156/test/software/model/software_type/cracker/process_type_test.exs#L24)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

If/when you need this function again before working on file_modules, move it to SoftwareFactory, with `:cracker` or `:$file_type` being passed as argument.
</blockquote></details>

Read the comment above; this will be removed when file modules become just a model attribute (it's the next PR i am doing this week)

---

*[test/software/model/software_type/log_forge/process_type_test.exs, line 23 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/249#-KrYVfCniobCpJRfeJ6F:-KrYXKEdSMZa-Wo6dXnW:bz48hey) ([raw file](https://github.com/hackerexperience/helix/blob/948a58afd5b3b11f39ee8a4aec57a9b935b00156/test/software/model/software_type/log_forge/process_type_test.exs#L23)):*
> Read the comment above; this will be removed when file modules become just a model attribute (it's the next PR i am doing this week)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/249)*

**Comment by renatomassaro** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[lib/process/event/cracker.ex, line 48 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/249#-KrYMaLuCa8aCJfgW1-Q:-KrZE8wNtIGQmW4E6f38:bxo2wno) ([raw file](https://github.com/hackerexperience/helix/blob/948a58afd5b3b11f39ee8a4aec57a9b935b00156/lib/process/event/cracker.ex#L48)):*
<details><summary><i>Previously, mememori (Charlotte Lorelei Oliveira) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Please use `docp`. It highlights better, and it is much easier to extend to multilines (plus more readable in that case too). 

---

*[lib/process/event/cracker.ex, line 62 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/249#-KrYMrw9IL3cnm4GFO3R:-KrZEMvd22wPM3XRmMyV:bxo2wno) ([raw file](https://github.com/hackerexperience/helix/blob/948a58afd5b3b11f39ee8a4aec57a9b935b00156/lib/process/event/cracker.ex#L62)):*
<details><summary><i>Previously, mememori (Charlotte Lorelei Oliveira) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Please use `docp`. It highlights better, and it is much easier to extend to multilines (plus more readable in that case too). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/249)*

**Comment by renatomassaro** [comment]
I missed one thing: please add a test case for cracker under file flow. 

It would also be beneficial if you could test the entire life cycle of the operation. For instance, in the case of log forge edit: test from process creation to finish, that the log was edited. This kind of test is the most effective one, if it passes you can get a very high degree of confidence that the feature is working as expected, not only its internal parts.

**Comment by mememori** [comment]
> I missed one thing: please add a test case for cracker under file flow.

My bad, i intended to include that but it seems i forgot to (and it also is not testing the reaction to firewallstarted/stopped event, nor the cracker complete event). I'm going to add those tests now

**Pull request merged**
