### PR TITLE
Add endpoint for webhook for account migration

### PR DESCRIPTION
**Pull request by mememori**
Also temporarily disables registration since we need to check if an username is allowed

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/helix/201)

### CODE REVIEW

**Comment by kress95** [comment]
Just a side note about registration:

Migration is allowing up to 15 characters (as this was HE legacy's limit), I believe that helix limit is just 14 characters, this might (or not) need to change.

Obviously, this is not a database constraint, it's checked on the application layer, like on helix.

**Comment by TheHeroBrine422** [comment]
Hey when is Heborn coming out?

**Comment by TheHeroBrine422** [comment]
When is Heborn coming out and why did you delete my comment?

**Comment by mememori** [comment]
> When is Heborn coming out and why did you delete my comment?

Because this is not the place for this. PLEASE don't spam the code repository with things not related directly to the code.

Email directly renato or ask on chatops so, as soon as he's able, he hopefully will answer. I am not the one who decides or knows such things.

As such, i'll remove any comment/issue/??? not directly related to helix code

**Comment by kress95** [comment]
:lgtm:

---

Reviewed 8 of 9 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/201#-:-KjdC010LrDyMdrZB1Rk:bnfp4nl)*

**Pull request merged**
