### PR TITLE
Tag tests

### PR DESCRIPTION
**Pull request by kress95**
Tags existing tests, service tests are left out as they're getting deprecated asap.

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/helix/28)

### CODE REVIEW

**Comment by mememori** [comment]
Review status: 0 of 26 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/hackerexperience/helix/28#-KfmzPxa_rOtWCes_xad:-KfmzPxa_rOtWCes_xae:bux2c39) (no related file):*
> Tags existing tests, service tests are left out as they're getting deprecated asap.

It's true that we'll deprecate the `services`, but while we are not doing it, they are one of our ways to ensure our code is working and thus should be tagged (it won't take you more than a few seconds to tag them) so our CI could test them

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/28)*

**Comment by mememori** [comment]
*[a discussion](https://reviewable.io:443/reviews/hackerexperience/helix/28#-KfmzPxa_rOtWCes_xad:-KfmzLSvdtH83CRalu9Y:b-66nfyi) (no related file):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

> Tags existing tests, service tests are left out as they're getting deprecated asap.

It's true that we'll deprecate the `services`, but while we are not doing it, they are one of our ways to ensure our code is working and thus should be tagged (it won't take you more than a few seconds to tag them) so our CI could test them
</blockquote></details>

Also, should i mention that because you didn't tag the Service tests i can't exclude them to test if my fake ecto adapter works ?

```
mix test --only unit --no-prune --trace
```
^^^ still executes service tests

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/28)*

**Comment by kress95** [comment]
*[a discussion](https://reviewable.io:443/reviews/hackerexperience/helix/28#-KfmzPxa_rOtWCes_xad:-KfprSWMi3qGwSZ2XkMq:b-68u9zo) (no related file):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

Also, should i mention that because you didn't tag the Service tests i can't exclude them to test if my fake ecto adapter works ?

```
mix test --only unit --no-prune --trace
```
^^^ still executes service tests
</blockquote></details>

I'll tag them asap.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/28)*

**Comment by mememori** [comment]
Review status: 0 of 30 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/hackerexperience/helix/28#-KfmzPxa_rOtWCes_xad:-KfqXcqY51yWVIKMm9er:bsq85p5) (no related file):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

I'll tag them asap.
</blockquote></details>

Not resolved, there are still tests that use database but are tagged as unit

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/28)*

**Comment by kress95** [comment]
*[a discussion](https://reviewable.io:443/reviews/hackerexperience/helix/28#-KfmzPxa_rOtWCes_xad:-Kfqw6tNdBtyklWdaoFe:b-hl9n16) (no related file):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

Not resolved, there are still tests that use database but are tagged as unit
</blockquote></details>

I'll check everything again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/28)*

**Comment by mememori** [comment]
This PR **is not** complete. I still get database errors when trying to run without any db data

```
Finished in 0.3 seconds
36 tests, 2 failures, 34 skipped
```

Please, ensure that the PR you want reviewed is complete before you move it again to the "Review" pipeline.

To do so, execute the appropriate tests to ensure that the purpose of the PR is achieved (this might include debugging directly on the database or on the interactive terminal) and review it yourself; if it seems ok after that, then move it to my review pipeline

**Comment by kress95** [comment]
Well, this is really weird:

```
$ mix ecto.drop && mix test --only unit --no-prune --trace
hell
  4 tests, 0 failures
helix_core
  1 test, 0 failures, 1 skipped
helix_account
  26 tests, 0 failures, 24 skipped
helix_entity
  20 tests, 0 failures, 20 skipped
helix_hardware
  21 tests, 0 failures, 19 skipped
helix_log
  5 tests, 0 failures, 4 skipped
helix_npc
  4 tests, 0 failures, 4 skipped
helix_process
  31 tests, 0 failures, 10 skipped
helix_server
  8 tests, 0 failures, 8 skipped
helix_software
  36 tests, 0 failures, 34 skipped
```

**Comment by mememori** [comment]
@kress95 
With your command (`mix ecto.drop && mix test --exclude integration --no-prune --trace`), do the following:

1) Go to `apps/helix_software/test/test_helper.exs`
2) Add the following snippet before `ExUnit.start()`: `IO.inspect Helix.Software.Repo.all Helix.Software.Model.File`
3) Run your command again

**Comment by kress95** [comment]
Found the problem, but I really wanted to know why ecto.drop isn't dropping Software :S

**Comment by mememori** [comment]
> Found the problem, but I really wanted to know why ecto.drop isn't dropping Software :S

All mix tasks run, by default, on `dev` environment. `test` runs only on `test` environment.

When you run `mix ecto.drop && mix test` you did the exactly same as 
```
> MIX_ENV=dev mix ecto.drop
> MIX_ENV=test mix test
```

And since test doesn't uses dev databases, nothing happened

**Comment by kress95** [comment]
So still I'm not used with the separated dbs... I'm fixing the remaining problems.

**Comment by mememori** [comment]
Just have some fun with `MIX_ENV=test mix do clean, compile, ecto.drop, ecto.create, test --only unit --no-prune --trace`

**Comment by mememori** [comment]
Okay, now try the opposite

`MIX_ENV=test mix do clean, compile, ecto.drop, ecto.create, test --exclude unit --no-prune --trace`

Tell me how many tests passes without depending on the database.

Now take a quick look at their code, do they depend on:
a) Sending or receiving messages from actors (like ets tables, ecto repos, sockets, external databases, k/v, buckets etc)

If true, they are in fact integration tests that aren't using the database, otherwise they are unit tests (because, after all, actor model requires you to send/receive messages to interact with other components)

**Comment by kress95** [comment]
There are some controller tests passing, but I don't like making

- account creation fails when password is too short

an unitary test, unless of course, we move it to model tests

however, :top: plan tests must be unitary

**Comment by kress95** [comment]
I believe that this is :top:  now

**Comment by mememori** [comment]
:lgtm:

---

Reviewed 29 of 30 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/28#-:-KfrhgO1J_NMCdf01_JL:bnfp4nl)*

**Pull request merged**
