### PR TITLE
Bank connections, tokens & account hack

### PR DESCRIPTION
**Pull request by renatomassaro**
Depends on #239 and #249 

- [x] Wire transfer
- [x] Bank token
- [x] Account hack with BufferOverflow attack[1]
  - [x] Overflow on WireTransfer connection
  - [x] Overflow on BankLogin connection
- [x] Token -> Password
- [x] Bank login with password
- [x] Bank login with token
- [x] Login connection
- [x] Bank data on Database
- [x] Bank account logout

---

[1] - it's not fully implement with Cracker to avoid conflicts with #249. Once it's merged, I'll add BufferOverflow as a module of Cracker, and merge both (like LogForger create/edit). 

(Note to self: merging is not a *requirement*, and if both (file) modules behave differently enough, it does make sense to keep them on separate (elixir) modules)

---

Incidental:

- [x] Refactor (Hacked)Database
- [x] Major refactor on Support
- [x] Create module's Setup for reliable and integrated game data generation
- [x] Meta data on Connection
- [x] TunnelAction API enhancement with `close_connections_where/4`

Yeah, this stuff will bloat this PR, but 1) it was a pain point 2) many bank-related tests would need refactor anyway 3) a different PR would depend on this one (and this one would depend on the other PR) 4) just do it

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/helix/250)

### CODE REVIEW

**Comment by renatomassaro** [comment]
@mememori now that there are a lot of integrated tests, we are getting a high rate of username collision. You might want to prioritize this issue: https://github.com/HackerExperience/burette/issues/4

**Comment by mememori** [comment]
> @mememori now that there are a lot of integrated tests, we are getting a high rate of username collision. You might want to prioritize this issue: HackerExperience/burette#4

Okay. Leave it to me

**Comment by renatomassaro** [comment]
As far as Bank is concerned, this PR is finished. However, I still have to:

- [ ] Fix dialyzer errors from PR #239 (elixir bug)
- [ ] Rebase/merge `master` and `bank` here
- [ ] Fix dialyzer error from handling of event CrackerConclusion. This one I've been postponing because it actually needs a refactor on Cracker + Entity, but I'll do on this PR (since this PR makes a complete overhaul on Entity's Database).

@mememori with that in mind, you can start your review process. Good luck. Meanwhile I'll start Bitcoin (based on this PR).

**Comment by renatomassaro** [comment]
Reviewed 153 of 184 files at r1, 19 of 36 files at r2, 16 of 18 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/250)*

**Pull request merged**
