### PR TITLE
Refactor `Log.find` into `Log.fetch`

### PR DESCRIPTION
**Pull request by kress95**
---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/helix/69)

### CODE REVIEW

**Comment by mememori** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[apps/helix_log/lib/log/controller/log.ex, line 52 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/69#-KgQ11NdkznQ3MQiiWPD:-KgQ11NdkznQ3MQiiWPE:b-p62hv9) ([raw file](https://github.com/hackerexperience/helix/blob/770a608531369422e0234d508524fd2c1d8aee0e/apps/helix_log/lib/log/controller/log.ex#L52)):*
> ```Elixir
>   @spec fetch(PK.t) :: Log.t | nil
>   def fetch(log_id),
>     do: Repo.get_by(Log, log_id: log_id)
> ```

`Repo.get`

---

*[apps/helix_log/lib/log/controller/log.ex, line 147 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/69#-KgQ19XW08oS2pPZ2TJg:-KgQ19XW08oS2pPZ2TJh:bjwyzzg) ([raw file](https://github.com/hackerexperience/helix/blob/770a608531369422e0234d508524fd2c1d8aee0e/apps/helix_log/lib/log/controller/log.ex#L147)):*
> ```Elixir
>     do: Log.Query.by_server(query, server_id)
>   defp reduce_find_params({:crypto_version, version}, query),
>     do: Log.Query.by_crypto_version(query, version)
> ```

Well, drop this. You didn't get the idea of `crypto_version`, let's leave it without any impl until we discuss encryption/decryption of logs

---

*[apps/helix_log/lib/log/model/log.ex, line 113 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/69#-KgQ1HyEQJBYHDYq2UfM:-KgQ1HyEQJBYHDYq2UfN:b-nyml2u) ([raw file](https://github.com/hackerexperience/helix/blob/770a608531369422e0234d508524fd2c1d8aee0e/apps/helix_log/lib/log/model/log.ex#L113)):*
> ```Elixir
>       do: where(query, [l], is_nil(l.crypto_version))
>     def by_crypto_version(query, crypto_version),
>       do: where(query, [l], l.crypto_version == ^crypto_version)
> ```

drop this

---

*[apps/helix_log/lib/log/model/log.ex, line 117 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/69#-KgQ1WIBOXni5AiYFpmU:-KgQ1WIBOXni5AiYFpmV:bi8i97d) ([raw file](https://github.com/hackerexperience/helix/blob/770a608531369422e0234d508524fd2c1d8aee0e/apps/helix_log/lib/log/model/log.ex#L117)):*
> ```Elixir
>     @spec by_message(Ecto.Queryable.t, String.t) :: Ecto.Queryable.t
>     def by_message(query \\ Log, message),
>       do: where(query, [l], like(l.message, ^message))
> ```

I am unsure if this is the ideal interface as it would require the requesting party to provide the query (ie: `find(server_id: id, message: "% has logged in%")`)

---

*[apps/helix_log/test/log/controller/log_test.exs, line 23 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/69#-KgQ2TDUM3xT4g7X_yXa:-KgQ2TDUM3xT4g7X_yXb:b-8gv556) ([raw file](https://github.com/hackerexperience/helix/blob/770a608531369422e0234d508524fd2c1d8aee0e/apps/helix_log/test/log/controller/log_test.exs#L23)):*
> ```Elixir
> 
>     fields = Map.merge(defaults, :maps.from_list(params))
>     Repo.insert!(struct(Log, fields))
> ```

This doesn't include children records that are necessary for most functions.

prefer

```elixir
defaults
|> Map.merge(params)
|> Log.create_changeset()
|> Repo.insert!()
```

---

*[apps/helix_log/test/log/controller/log_test.exs, line 70 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/69#-KgQ2iV2A3OR0VR809Y8:-KgQ2iV2A3OR0VR809Y9:b-2r41yx) ([raw file](https://github.com/hackerexperience/helix/blob/770a608531369422e0234d508524fd2c1d8aee0e/apps/helix_log/test/log/controller/log_test.exs#L70)):*
> ```Elixir
>     end
> 
>     test "fails when log with id doesn't exist" do
> ```

fails when log doesn't exist

---

*[apps/helix_log/test/log/controller/log_test.exs, line 88 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/69#-KgQ2qIHQd9fT7qm69Bo:-KgQ2qIHQd9fT7qm69Bp:b-40kih8) ([raw file](https://github.com/hackerexperience/helix/blob/770a608531369422e0234d508524fd2c1d8aee0e/apps/helix_log/test/log/controller/log_test.exs#L88)):*
> ```Elixir
> 
>       assert log.log_id == got.log_id
>     end
> ```

This is wrong

---

*[apps/helix_log/test/log/controller/log_test.exs, line 95 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/69#-KgQ2wFMIsV-TIm1tcT2:-KgQ2wFMIsV-TIm1tcT3:b-3d510l) ([raw file](https://github.com/hackerexperience/helix/blob/770a608531369422e0234d508524fd2c1d8aee0e/apps/helix_log/test/log/controller/log_test.exs#L95)):*
> ```Elixir
> 
>       assert log.log_id == got.log_id
>     end
> ```

This is in most part wrong

---

*[apps/helix_log/test/log/controller/log_test.exs, line 106 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/69#-KgQ32MSMf6DARWTDwQ3:-KgQ32MSMf6DARWTDwQ4:b-h8917w) ([raw file](https://github.com/hackerexperience/helix/blob/770a608531369422e0234d508524fd2c1d8aee0e/apps/helix_log/test/log/controller/log_test.exs#L106)):*
> ```Elixir
>       result = Controller.find(crypto_version: 0)
>       assert Enum.empty?(result)
>     end
> ```

this is wrong

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/69)*

**Comment by kress95** [comment]
*[apps/helix_log/lib/log/model/log.ex, line 117 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/69#-KgQ1WIBOXni5AiYFpmU:-KgQHTzMCoMLgnCZ46I5:brs4m4p) ([raw file](https://github.com/hackerexperience/helix/blob/770a608531369422e0234d508524fd2c1d8aee0e/apps/helix_log/lib/log/model/log.ex#L117)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

I am unsure if this is the ideal interface as it would require the requesting party to provide the query (ie: `find(server_id: id, message: "% has logged in%")`)
</blockquote></details>

You mean this should include the "% %" automatically?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/69)*

**Comment by kress95** [comment]
*[apps/helix_log/test/log/controller/log_test.exs, line 95 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/69#-KgQ2wFMIsV-TIm1tcT2:-KgQJE76rnzTYeQp3XpQ:bn2rnj6) ([raw file](https://github.com/hackerexperience/helix/blob/770a608531369422e0234d508524fd2c1d8aee0e/apps/helix_log/test/log/controller/log_test.exs#L95)):*
> fails when log doesn't exist
The problem is that the ideia is testing it yielding many results instead of one, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/69)*

**Comment by kress95** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[apps/helix_log/lib/log/controller/log.ex, line 52 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/69#-KgQ11NdkznQ3MQiiWPD:-KgQJUqe2pCRWb9eDEC7:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/770a608531369422e0234d508524fd2c1d8aee0e/apps/helix_log/lib/log/controller/log.ex#L52)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

`Repo.get`
</blockquote></details>

Done.

---

*[apps/helix_log/lib/log/controller/log.ex, line 147 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/69#-KgQ19XW08oS2pPZ2TJg:-KgQJZA-O2wbMAx03azK:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/770a608531369422e0234d508524fd2c1d8aee0e/apps/helix_log/lib/log/controller/log.ex#L147)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

Well, drop this. You didn't get the idea of `crypto_version`, let's leave it without any impl until we discuss encryption/decryption of logs
</blockquote></details>

Done.

---

*[apps/helix_log/lib/log/model/log.ex, line 113 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/69#-KgQ1HyEQJBYHDYq2UfM:-KgQJac0RTuCLNkOV-md:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/770a608531369422e0234d508524fd2c1d8aee0e/apps/helix_log/lib/log/model/log.ex#L113)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

drop this
</blockquote></details>

Done.

---

*[apps/helix_log/test/log/controller/log_test.exs, line 23 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/69#-KgQ2TDUM3xT4g7X_yXa:-KgQJ2SUXsJYIObPe9oT:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/770a608531369422e0234d508524fd2c1d8aee0e/apps/helix_log/test/log/controller/log_test.exs#L23)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

This doesn't include children records that are necessary for most functions.

prefer

```elixir
defaults
|> Map.merge(params)
|> Log.create_changeset()
|> Repo.insert!()
```
</blockquote></details>

Done.

---

*[apps/helix_log/test/log/controller/log_test.exs, line 70 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/69#-KgQ2iV2A3OR0VR809Y8:-KgQJe6XPt2aDOz_8kMi:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/770a608531369422e0234d508524fd2c1d8aee0e/apps/helix_log/test/log/controller/log_test.exs#L70)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

fails when log doesn't exist
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/69)*

**Comment by mememori** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[apps/helix_log/lib/log/model/log.ex, line 117 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/69#-KgQ1WIBOXni5AiYFpmU:-KgRG_id6uOAm1aIGH60:b7mugfs) ([raw file](https://github.com/hackerexperience/helix/blob/770a608531369422e0234d508524fd2c1d8aee0e/apps/helix_log/lib/log/model/log.ex#L117)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

You mean this should include the "% %" automatically?
</blockquote></details>

Most likely. But let's leave it as it is right now. Let's delegate that to the API

---

*[apps/helix_log/test/log/controller/log_test.exs, line 95 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/69#-KgQ2wFMIsV-TIm1tcT2:-KgRGw5ydBotAfWc7t0p:b5m7wuf) ([raw file](https://github.com/hackerexperience/helix/blob/770a608531369422e0234d508524fd2c1d8aee0e/apps/helix_log/test/log/controller/log_test.exs#L95)):*
<details><summary><i>Previously, kress95 (Christian Ferraz Lemos de Sousa) wrote…</i></summary><blockquote>

> fails when log doesn't exist
The problem is that the ideia is testing it yielding many results instead of one, right?
</blockquote></details>

Well, i meant that i wanted to test that it uses `like` properly, but let's leave that to the API tests then

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/69#-:-KgRHByVfesfg0pl5N7V:bnfp4nl)*

**Pull request merged**
