### PR TITLE
Even more LogForger

### LINKED ISSUE #197: LogForge process
- Edit log message
- Forge new log
- Emit events

### PR DESCRIPTION
**Pull request by mememori**
Closes #197 

- Improve Log test coverage
- Improve LogForge test coverage
- Improve Log documentation
- Implements LogForge create functionality

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/helix/237)

### CODE REVIEW

**Comment by renatomassaro** [comment]
I'll review tomorrow morning. It's not directly related to this PR (and may be done on another one), but just to remind you: fix those tests you've added as pending on #225. IIRC there were three of them

**Comment by renatomassaro** [comment]
Reviewed 22 of 30 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[lib/software/action/flow/cracker.ex, line 52 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrMuHMAqjqOIGhZAnSD:-KrMuHMBkwA01AEKooyx:bx6m6c8) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/lib/software/action/flow/cracker.ex#L52)):*
> ```Elixir
>     flowing do
>       with {:ok, process, events} <- ProcessAction.create(params) do
>         Event.emit(events)
> ```

Small inconsistency here. file_download flow you are emitting events inside the with clause, using `on_success`. Here you are emitting outside. I think we should be consistent on this regard, since we'll have many flows with the same format (all or most of them emitting events).

Personally I prefer the format on file_download flow. It removes the need to accumulate all events from all calls.

---

*[test/process/query/process_test.exs, line 66 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrMyxZXv-_NDWsDc2tm:-KrMyxZXv-_NDWsDc2tn:b-rxxkbt) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/test/process/query/process_test.exs#L66)):*
> ```Elixir
> 
>       TOPHelper.top_stop(server)
>       CacheHelper.sync_test()
> ```

I don't think this sync here is needed, since nothing related to software/processes is cached. It would perform a noop though (single ETS lookup), so no harm done.

---

*[test/process/query/process_test.exs, line 108 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrMzRYuZIM_oVgvzLkM:-KrMzRYvA27CNl3CP8Gg:bb73xfv) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/test/process/query/process_test.exs#L108)):*
> ```Elixir
> 
>       TOPHelper.top_stop(server)
>       CacheHelper.sync_test()
> ```

Same

---

*[test/process/query/process_test.exs, line 152 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrMzSYS8XGoq1trR8KH:-KrMzSYS8XGoq1trR8KI:bb73xfv) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/test/process/query/process_test.exs#L152)):*
> ```Elixir
>       TOPHelper.top_stop(server1)
>       TOPHelper.top_stop(server2)
>       CacheHelper.sync_test()
> ```

Same

---

*[test/software/action/flow/file_test.exs, line 32 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrN-RbwOULOmLs1LGHe:-KrN-RbwOULOmLs1LGHf:b-krrwtz) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/test/software/action/flow/file_test.exs#L32)):*
> ```Elixir
> 
>       storage =
>         server.motherboard_id
> ```

CacheQuery.from_server_get_storages()

(While you are at it, do a quick search on older tests that could be simplified as well)

---

*[test/software/action/flow/file_test.exs, line 44 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrMzqzy8KXMxp16N-Au:-KrMzqzy8KXMxp16N-Av:bcvjuec) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/test/software/action/flow/file_test.exs#L44)):*
> ```Elixir
>       file = Factory.insert(:file, software_type: :firewall, storage: storage)
>       modules = %{firewall_passive: 100}
>       # FIXME: this function should exist on the FileAction
> ```

Fix it. It's quick and solves three problems on this test alone

---

*[test/software/action/flow/file_test.exs, line 53 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrMzeVzV-_5VI7olPkM:-KrMzeVzV-_5VI7olPkN:bb73xfv) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/test/software/action/flow/file_test.exs#L53)):*
> ```Elixir
> 
>       TOPHelper.top_stop(server)
>       CacheHelper.sync_test()
> ```

Same

---

*[test/software/action/flow/file_test.exs, line 67 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrN-KyY2z-Cn0FE_VQ_:-KrN-KyY2z-Cn0FE_VQa:b-ljui9g) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/test/software/action/flow/file_test.exs#L67)):*
> ```Elixir
> 
>       storage =
>         server.motherboard_id
> ```

CacheQuery.from_server_get_storages()

---

*[test/software/action/flow/file_test.exs, line 98 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrN-Iyq_pdsw2KfzheZ:-KrN-Iyq_pdsw2Kfzhe_:b-ljui9g) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/test/software/action/flow/file_test.exs#L98)):*
> ```Elixir
> 
>       storage =
>         server.motherboard_id
> ```

CacheQuery.from_server_get_storages()

---

*[test/software/action/flow/file_test.exs, line 129 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrN-2421MFkD6wA-_2C:-KrN-2421MFkD6wA-_2D:bb73xfv) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/test/software/action/flow/file_test.exs#L129)):*
> ```Elixir
> 
>       TOPHelper.top_stop(server)
>       CacheHelper.sync_test()
> ```

Same

---

*[test/software/action/flow/file_test.exs, line 142 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrN-9h4FRLJB8eszU5N:-KrN-9h4FRLJB8eszU5O:b-ljui9g) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/test/software/action/flow/file_test.exs#L142)):*
> ```Elixir
>       CacheHelper.sync_test()
> 
>       storage =
> ```

CacheQuery.from_server_get_storages()

---

*[test/software/action/flow/file_test.exs, line 174 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrN-4kMI-tfKGdJHsy3:-KrN-4kMI-tfKGdJHsy4:bb73xfv) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/test/software/action/flow/file_test.exs#L174)):*
> ```Elixir
>       TOPHelper.top_stop(server)
> 
>       CacheHelper.sync_test()
> ```

Same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/237)*

**Comment by mememori** [comment]
Review status: 28 of 30 files reviewed at latest revision, 12 unresolved discussions.

---

*[lib/software/action/flow/cracker.ex, line 52 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrMuHMAqjqOIGhZAnSD:-KrN5Sa73bjTkYSbpbIs:b-fkxcvz) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/lib/software/action/flow/cracker.ex#L52)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

Small inconsistency here. file_download flow you are emitting events inside the with clause, using `on_success`. Here you are emitting outside. I think we should be consistent on this regard, since we'll have many flows with the same format (all or most of them emitting events).

Personally I prefer the format on file_download flow. It removes the need to accumulate all events from all calls.
</blockquote></details>

I didn't change the cracker flow (besides fixing it) because it'll be merged onto flow/file later, so i prefered to just fix it ASAP and leave consistency, testing etc to another PR dedicated solely to the cracker flow part

---

*[test/process/query/process_test.exs, line 66 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrMyxZXv-_NDWsDc2tm:-KrN5mNh56lZsHksPeTr:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/test/process/query/process_test.exs#L66)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

I don't think this sync here is needed, since nothing related to software/processes is cached. It would perform a noop though (single ETS lookup), so no harm done.
</blockquote></details>

Done.

---

*[test/process/query/process_test.exs, line 108 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrMzRYuZIM_oVgvzLkM:-KrN5tO4N_VIl2672EYY:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/test/process/query/process_test.exs#L108)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.

---

*[test/process/query/process_test.exs, line 152 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrMzSYS8XGoq1trR8KH:-KrN5tue6WfVuSluxS5Q:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/test/process/query/process_test.exs#L152)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.

---

*[test/software/action/flow/file_test.exs, line 32 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrN-RbwOULOmLs1LGHe:-KrN6IPjDDkP1polslyV:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/test/software/action/flow/file_test.exs#L32)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

CacheQuery.from_server_get_storages()

(While you are at it, do a quick search on older tests that could be simplified as well)
</blockquote></details>

Done.

---

*[test/software/action/flow/file_test.exs, line 44 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrMzqzy8KXMxp16N-Au:-KrN6JGjkKhqVKFCdPGc:bqy3ryk) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/test/software/action/flow/file_test.exs#L44)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

Fix it. It's quick and solves three problems on this test alone
</blockquote></details>

I didn't do it because it's on my TODO fixing file_module, so i'll fix that while i'm on it

---

*[test/software/action/flow/file_test.exs, line 53 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrMzeVzV-_5VI7olPkM:-KrN6WrcDFelKCLz0YDf:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/test/software/action/flow/file_test.exs#L53)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.

---

*[test/software/action/flow/file_test.exs, line 67 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrN-KyY2z-Cn0FE_VQ_:-KrN6XbOlbUVMC0p2g62:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/test/software/action/flow/file_test.exs#L67)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

CacheQuery.from_server_get_storages()
</blockquote></details>

Done.

---

*[test/software/action/flow/file_test.exs, line 98 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrN-Iyq_pdsw2KfzheZ:-KrN6YUFZ33zUozx0P3U:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/test/software/action/flow/file_test.exs#L98)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

CacheQuery.from_server_get_storages()
</blockquote></details>

Done.

---

*[test/software/action/flow/file_test.exs, line 129 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrN-2421MFkD6wA-_2C:-KrN6Z9Gs2tR8Ck5WA2B:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/test/software/action/flow/file_test.exs#L129)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.

---

*[test/software/action/flow/file_test.exs, line 142 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrN-9h4FRLJB8eszU5N:-KrN6cCdFloffZ0aWdeV:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/test/software/action/flow/file_test.exs#L142)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

CacheQuery.from_server_get_storages()
</blockquote></details>

Done.

---

*[test/software/action/flow/file_test.exs, line 174 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrN-4kMI-tfKGdJHsy3:-KrN6d0kP_PE9VN2Kmt1:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/test/software/action/flow/file_test.exs#L174)):*
<details><summary><i>Previously, renatomassaro (Renato Massaro) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/237)*

**Comment by renatomassaro** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/software/action/flow/cracker.ex, line 52 at r2](https://reviewable.io:443/reviews/hackerexperience/helix/237#-KrMuHMAqjqOIGhZAnSD:-KrNAnzu28k29fu2heR3:blon1k8) ([raw file](https://github.com/hackerexperience/helix/blob/4960fd8853547e629ddf4ca1dfa3fd1b637c4bd9/lib/software/action/flow/cracker.ex#L52)):*
Ok, but what is the format/model we should use?

And for the record, I highly recommend you fix any issue the moment you spot it. Recently read this: https://www.saturnflyer.com/blog/fix-it-now
If anything, this quote makes the most sense:

> Right NOW we understand the problem. We have time to understand it AND its solution. In the future we'll have to figure that out again. New problems, new ideas, and new priorities will call for our attention.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/237#-:-KrNBRHI-goH2ezxlI5q:bnfp4nl)*

**Pull request merged**
