### PR TITLE
Update Server fetch/find 

### PR DESCRIPTION
**Pull request by kress95**
Almost disables ServerService (comments every GenServer call/cast handler) and then updates everything to follow current conventions.

Some tests are still lacking, (some will need resources from another domains), I don't think I should add them right now.

---
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/helix/73)

### CODE REVIEW

**Comment by mememori** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[apps/helix_server/lib/server/controller/server.ex, line 15 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/73#-KgRHYz1C3tQ2YDLpGot:-KgRHYz2z-089Fft1GQN:b-7ep9h6) ([raw file](https://github.com/hackerexperience/helix/blob/91b650c6697bd3de8ee4d40c5e4ae7ba54ec5a5e/apps/helix_server/lib/server/controller/server.ex#L15)):*
> ```Elixir
>   @spec create(Server.creation_params) ::
>     {:ok, Server.t}
>     | {:error, reason :: term}
> ```

Don't it return an `Ecto.Changeset.t` on error ?

---

*[apps/helix_server/lib/server/controller/server.ex, line 39 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/73#-KgRHg5OREbgYUasj8DZ:-KgRHg5OREbgYUasj8D_:b-7ep9h6) ([raw file](https://github.com/hackerexperience/helix/blob/91b650c6697bd3de8ee4d40c5e4ae7ba54ec5a5e/apps/helix_server/lib/server/controller/server.ex#L39)):*
> ```Elixir
>   @spec update(Server.t, Server.update_params) ::
>     {:ok, Server.t}
>     | {:error, reason :: term}
> ```

Don't it return an `Ecto.Changeset.t` on error ?

---

*[apps/helix_server/lib/server/controller/server.ex, line 83 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/73#-KgRHxRaEv6Fu8V_j-s1:-KgRHxRaEv6Fu8V_j-s2:bn08dw9) ([raw file](https://github.com/hackerexperience/helix/blob/91b650c6697bd3de8ee4d40c5e4ae7ba54ec5a5e/apps/helix_server/lib/server/controller/server.ex#L83)):*
> ```Elixir
>   @spec reduce_find_params(find_param, Ecto.Queryable.t) :: Ecto.Queryable.t
>   defp reduce_find_params({:id, several_ids}, query),
>     do: Server.Query.from_id_list(query, several_ids)
> ```

`id_list`

---

*[apps/helix_server/test/controller/server_test.exs, line 107 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/73#-KgRIS6wpO5k3QRU2Egr:-KgRIS6wpO5k3QRU2Egs:b-vfxwfc) ([raw file](https://github.com/hackerexperience/helix/blob/91b650c6697bd3de8ee4d40c5e4ae7ba54ec5a5e/apps/helix_server/test/controller/server_test.exs#L107)):*
> ```Elixir
> 
>       result = Enum.all?(expected, &(&1 in found))
>       assert result
> ```

Why did you write that in two lines when it would be as readable in one ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/73)*

**Comment by mememori** [comment]
Mark as done the concerns you resolve, please

**Comment by kress95** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[apps/helix_server/lib/server/controller/server.ex, line 15 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/73#-KgRHYz1C3tQ2YDLpGot:-KgV1E-bcfQzlvUDguKI:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/91b650c6697bd3de8ee4d40c5e4ae7ba54ec5a5e/apps/helix_server/lib/server/controller/server.ex#L15)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

Don't it return an `Ecto.Changeset.t` on error ?
</blockquote></details>

Done.

---

*[apps/helix_server/lib/server/controller/server.ex, line 39 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/73#-KgRHg5OREbgYUasj8DZ:-KgV1EXXx9fAS4M1Rsbq:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/91b650c6697bd3de8ee4d40c5e4ae7ba54ec5a5e/apps/helix_server/lib/server/controller/server.ex#L39)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

Don't it return an `Ecto.Changeset.t` on error ?
</blockquote></details>

Done.

---

*[apps/helix_server/lib/server/controller/server.ex, line 83 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/73#-KgRHxRaEv6Fu8V_j-s1:-KgV1FDFJbB0NlxOJKV4:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/91b650c6697bd3de8ee4d40c5e4ae7ba54ec5a5e/apps/helix_server/lib/server/controller/server.ex#L83)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

`id_list`
</blockquote></details>

Done.

---

*[apps/helix_server/test/controller/server_test.exs, line 107 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/73#-KgRIS6wpO5k3QRU2Egr:-KgV1GkGCLJ0qPGt5bi1:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/91b650c6697bd3de8ee4d40c5e4ae7ba54ec5a5e/apps/helix_server/test/controller/server_test.exs#L107)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

Why did you write that in two lines when it would be as readable in one ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/73)*

**Comment by mememori** [comment]
Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/73)*

**Pull request merged**
