### PR TITLE
Return JWT on account login

### PR DESCRIPTION
**Pull request by renatomassaro**
This change is [Reviewable](https://reviewable.io/reviews/hackerexperience/helix/87)

### CODE REVIEW

**Comment by mememori** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[apps/helix_account/lib/account.ex, line 32 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/87#-KgXAmHdHxmvjrmBUChv:-KgXAmHdHxmvjrmBUChw:b44u44) ([raw file](https://github.com/hackerexperience/helix/blob/07f3a7917a4f65e899b263f5de271aaedcbfd031/apps/helix_account/lib/account.ex#L32)):*
> ```Elixir
>     allowed_algos = Application.get_env(:guardian, Guardian)[:allowed_algos]
>     if "none" in allowed_algos do
>       raise "Can't use 'none' as JWT algorithm"
> ```

🙌

---

*[apps/helix_account/lib/account/controller/session.ex, line 13 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/87#-KgXAy7RCrGWtZO61wK6:-KgXAy7RCrGWtZO61wK7:b-pb9bm7) ([raw file](https://github.com/hackerexperience/helix/blob/07f3a7917a4f65e899b263f5de271aaedcbfd031/apps/helix_account/lib/account/controller/session.ex#L13)):*
> ```Elixir
>   @spec validate(Session.session) ::
>   {:ok, claims :: map}
>   | {:error, :unauthorized}
> ```

indent

---

*[apps/helix_account/lib/account/service/api/session.ex, line 15 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/87#-KgXCTZK7Dk1WifpW3rV:-KgXCTZK7Dk1WifpW3rW:bd5d6lg) ([raw file](https://github.com/hackerexperience/helix/blob/07f3a7917a4f65e899b263f5de271aaedcbfd031/apps/helix_account/lib/account/service/api/session.ex#L15)):*
> ```Elixir
>   @spec validate_token(Session.session) ::
>   {:ok, claims :: map}
>   | {:error, :unauthorized}
> ```

indentation

---

*[apps/helix_account/lib/ws/controller/account.ex, line 33 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/87#-KgXCinrtMThqbNlqfce:-KgXCinrtMThqbNlqfcf:bve41xu) ([raw file](https://github.com/hackerexperience/helix/blob/07f3a7917a4f65e899b263f5de271aaedcbfd031/apps/helix_account/lib/ws/controller/account.ex#L33)):*
> ```Elixir
>     case AccountAPI.login(username, password) do
>       {:ok, jwt} ->
>         {:ok, Helix.Account.WS.View.Account.format(%{:token => jwt})}
> ```

I would not run it throught the view format as it doesn't need to be format

---

*[apps/helix_account/lib/ws/view/account.ex, line 22 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/87#-KgXCgf3ls5WLQX7VhyB:-KgXCgf3ls5WLQX7VhyC:b-62faf6) ([raw file](https://github.com/hackerexperience/helix/blob/07f3a7917a4f65e899b263f5de271aaedcbfd031/apps/helix_account/lib/ws/view/account.ex#L22)):*
> ```Elixir
>   def format(value) do
>     value
>   end
> ```

I don't really like this

---

*[apps/helix_account/test/controller/session_test.exs, line 15 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/87#-KgXD8GAoltjYSSQpSMN:-KgXD8GAoltjYSSQpSMO:bnbvtul) ([raw file](https://github.com/hackerexperience/helix/blob/07f3a7917a4f65e899b263f5de271aaedcbfd031/apps/helix_account/test/controller/session_test.exs#L15)):*
> ```Elixir
>   describe "token generation" do
>     test "succeeds with valid account" do
>       params = Factory.account_factory()
> ```

use ExMachina's special secretly built-be-macro-and-not-that-much-documented `build(:account)`. `build(atom)` will simply execute `#{atom}_factory()`. You also have build/2, build_list/{2,3}, insert/{1,2}, insert_list/{2,3} and params_for/1

---

*[apps/helix_account/test/controller/session_test.exs, line 21 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/87#-KgXDi1yv_uzckhjDxbD:-KgXDi1yv_uzckhjDxbE:b-i9yzr0) ([raw file](https://github.com/hackerexperience/helix/blob/07f3a7917a4f65e899b263f5de271aaedcbfd031/apps/helix_account/test/controller/session_test.exs#L21)):*
>  necessary when we have type specs?
>       assert is_binary(token
Answer: not really. Unless the executed code is really obscure, dialyzer will compare the estimated generated final value with the spec return. Techincaly if the function says that it returns String.t but the last called function might return an integer without a clear clause, it could fail the contrat (as it is just success typed). So, tl;dr, i'd leave it here but it won't really make any difference

---

*[apps/helix_account/test/controller/session_test.exs, line 30 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/87#-KgXEIH8_yl1Sw2zSaYi:-KgXEIH8_yl1Sw2zSaYj:b-jao169) ([raw file](https://github.com/hackerexperience/helix/blob/07f3a7917a4f65e899b263f5de271aaedcbfd031/apps/helix_account/test/controller/session_test.exs#L30)):*
> ```Elixir
>     end
> ```

credo blank lines

---

*[apps/helix_account/test/controller/session_test.exs, line 51 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/87#-KgXEQK-RVuFpAuswQ5q:-KgXEQK-RVuFpAuswQ5r:b-mu0t41) ([raw file](https://github.com/hackerexperience/helix/blob/07f3a7917a4f65e899b263f5de271aaedcbfd031/apps/helix_account/test/controller/session_test.exs#L51)):*
> ```Elixir
>     end
>   end
> ```

remove this line

---

*[apps/helix_account/test/service/api/account_test.exs, line 61 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/87#-KgXEU3cyw7QMIbvw5lr:-KgXEU3cyw7QMIbvw5ls:bb6mt9b) ([raw file](https://github.com/hackerexperience/helix/blob/07f3a7917a4f65e899b263f5de271aaedcbfd031/apps/helix_account/test/service/api/account_test.exs#L61)):*
> ```Elixir
>       assert {:ok, token} = API.login(account.username, password)
>       assert {:ok, claims} = SessionAPI.validate_token(token)
>       assert account.account_id == claims["sub"]
> ```

:+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/87)*

**Comment by renatomassaro** [comment]
Review status: 2 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

*[apps/helix_account/lib/account/controller/session.ex, line 13 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/87#-KgXAy7RCrGWtZO61wK6:-KgXSjGGtL2M82h08fY1:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/07f3a7917a4f65e899b263f5de271aaedcbfd031/apps/helix_account/lib/account/controller/session.ex#L13)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

indent
</blockquote></details>

Done.

---

*[apps/helix_account/lib/account/service/api/session.ex, line 15 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/87#-KgXCTZK7Dk1WifpW3rV:-KgXSlJuuFB57Khk4MNU:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/07f3a7917a4f65e899b263f5de271aaedcbfd031/apps/helix_account/lib/account/service/api/session.ex#L15)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

indentation
</blockquote></details>

Done.

---

*[apps/helix_account/lib/ws/controller/account.ex, line 33 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/87#-KgXCinrtMThqbNlqfce:-KgXSmLOrO-o78AIn7Rq:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/07f3a7917a4f65e899b263f5de271aaedcbfd031/apps/helix_account/lib/ws/controller/account.ex#L33)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

I would not run it throught the view format as it doesn't need to be format
</blockquote></details>

Done.

---

*[apps/helix_account/test/controller/session_test.exs, line 15 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/87#-KgXD8GAoltjYSSQpSMN:-KgXTTOkYt-xrYSWq0Rk:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/07f3a7917a4f65e899b263f5de271aaedcbfd031/apps/helix_account/test/controller/session_test.exs#L15)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

use ExMachina's special secretly built-be-macro-and-not-that-much-documented `build(:account)`. `build(atom)` will simply execute `#{atom}_factory()`. You also have build/2, build_list/{2,3}, insert/{1,2}, insert_list/{2,3} and params_for/1
</blockquote></details>

Done.

---

*[apps/helix_account/test/controller/session_test.exs, line 21 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/87#-KgXDi1yv_uzckhjDxbD:-KgXTSr5EWketDUbkmbC:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/07f3a7917a4f65e899b263f5de271aaedcbfd031/apps/helix_account/test/controller/session_test.exs#L21)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

>  necessary when we have type specs?
>       assert is_binary(token
Answer: not really. Unless the executed code is really obscure, dialyzer will compare the estimated generated final value with the spec return. Techincaly if the function says that it returns String.t but the last called function might return an integer without a clear clause, it could fail the contrat (as it is just success typed). So, tl;dr, i'd leave it here but it won't really make any difference
</blockquote></details>

Done.

---

*[apps/helix_account/test/controller/session_test.exs, line 30 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/87#-KgXEIH8_yl1Sw2zSaYi:-KgXTUgZpL4eN5BIq7Dh:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/07f3a7917a4f65e899b263f5de271aaedcbfd031/apps/helix_account/test/controller/session_test.exs#L30)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

credo blank lines
</blockquote></details>

Done.

---

*[apps/helix_account/test/controller/session_test.exs, line 51 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/87#-KgXEQK-RVuFpAuswQ5q:-KgXTVAOm3JY7zy5VqA2:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/07f3a7917a4f65e899b263f5de271aaedcbfd031/apps/helix_account/test/controller/session_test.exs#L51)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

remove this line
</blockquote></details>

Done.

---

*[apps/helix_account/lib/ws/view/account.ex, line 22 at r1](https://reviewable.io:443/reviews/hackerexperience/helix/87#-KgXCgf3ls5WLQX7VhyB:-KgXTYV-GsShT4h8qrWv:b-896fix) ([raw file](https://github.com/hackerexperience/helix/blob/07f3a7917a4f65e899b263f5de271aaedcbfd031/apps/helix_account/lib/ws/view/account.ex#L22)):*
<details><summary><i>Previously, mememori (Charlotte '); DROP TABLE users;--) wrote…</i></summary><blockquote>

I don't really like this
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/87)*

**Comment by mememori** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hackerexperience/helix/87#-:-KgXUJQeY-xCZXtWQ2zc:bnfp4nl)*

**Comment by mememori** [comment]
> 
> :shipit: **lgtm** :shipit:

**Pull request merged**
